-- Table: hist_abs_daily_buchungen_abs
CREATE TABLE "hist_abs_daily_buchungen_abs" (
    "ABS_EFFECTIVE_DATE" text,
    "ABS_END_DATE" text,
    "ABS_FLAG_INACTIVE" text,
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_NAME_OWNER" text,
    "ABS_OFFER_DATE" text,
    "ABS_SETTLEMENT_DATE" text,
    "ABS_STATUS_SPV" text,
    "BEGIN_PERIODE" text,
    "DATUM_FI_BELEG" text,
    "DATUM_FI_CREATE" text,
    "DATUM_FI_GEBUCHT" text,
    "DATUM_FI_VALUTA" text,
    "FI_BETRAG" text,
    "FI_GEGENKONTO" text,
    "FI_GEGENKONTO_BEZ" text,
    "FI_ISINTREL" text,
    "FI_KONTO" text,
    "FI_KONTO_BEZ" text,
    "FI_NEBENKONTO" text,
    "FI_SOLLHABEN" text,
    "FI_STO_RESTORNODATUM" text,
    "FI_STO_RESTORNOFLAG" text,
    "FI_STO_STORNODATUM" text,
    "FI_STO_STORNOFLAG" text,
    "FI_STO_SYSFIORG" text,
    "FI_STO_SYSSTORNO" text,
    "FI_SYSFI" text,
    "FI_SYSFT" text,
    "FI_SYSPERSON" text,
    "FI_SYSVT" text,
    "FI_TEXT" text,
    "FLAG_FJ_PENDING" text,
    "ID_SYSFIJOUR" text,
    "KKL_GEGENKONTO" text,
    "KKL_GEGENKONTO_BEZ" text,
    "KKL_KONTO" text,
    "KKL_KONTO_BEZ" text,
    "KLASSIERUNG_ABS" text,
    "MWST_DIREKTBUCHUNG" text,
    "MWST_SYSMWST" text,
    "PERIODE" text,
    "RNMAHN_SYSRN" text,
    "RNMAHN_SYSRNMAHN" text,
    "RNPOS_SYSRN" text,
    "RNPOS_SYSRNPOS" text,
    "RNZAHL_SYSRN" text,
    "RNZAHL_SYSRNZAHL" text,
    "RNZAHL_SYSRNZAHLVER" text,
    "RNZAHL_ZAHLART" text,
    "SYSFIPERIOD" text,
    "SYSVART" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TP" text,
    "VT_SYSPERSON_OWNER" text,
    "WJ" text
);

-- Table: hist_abs_daily_cash_sweep_buchungen
CREATE TABLE "hist_abs_daily_cash_sweep_buchungen" (
    "ABS_EFFECTIVE_DATE" text,
    "ABS_END_DATE" text,
    "ABS_FLAG_INACTIVE" text,
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_NAME_OWNER" text,
    "ABS_OFFER_DATE" text,
    "ABS_SETTLEMENT_DATE" text,
    "ABS_STATUS_SPV" text,
    "BEGIN_PERIODE" text,
    "DATUM_FI_BELEG" text,
    "DATUM_FI_CREATE" text,
    "DATUM_FI_GEBUCHT" text,
    "DATUM_FI_VALUTA" text,
    "FI_BETRAG" text,
    "FI_GEGENKONTO" text,
    "FI_GEGENKONTO_BEZ" text,
    "FI_ISINTREL" text,
    "FI_KONTO" text,
    "FI_KONTO_BEZ" text,
    "FI_NEBENKONTO" text,
    "FI_SOLLHABEN" text,
    "FI_STO_RESTORNODATUM" text,
    "FI_STO_RESTORNOFLAG" text,
    "FI_STO_STORNODATUM" text,
    "FI_STO_STORNOFLAG" text,
    "FI_STO_SYSFIORG" text,
    "FI_STO_SYSSTORNO" text,
    "FI_SYSFI" text,
    "FI_SYSFT" text,
    "FI_SYSPERSON" text,
    "FI_SYSVT" text,
    "FI_TEXT" text,
    "FLAG_FJ_PENDING" text,
    "ID_SYSFIJOUR" text,
    "KKL_GEGENKONTO" text,
    "KKL_GEGENKONTO_BEZ" text,
    "KKL_KONTO" text,
    "KKL_KONTO_BEZ" text,
    "KLASSIERUNG_ABS" text,
    "MWST_DIREKTBUCHUNG" text,
    "MWST_SYSMWST" text,
    "PERIODE" text,
    "RNMAHN_SYSRN" text,
    "RNMAHN_SYSRNMAHN" text,
    "RNPOS_SYSRN" text,
    "RNPOS_SYSRNPOS" text,
    "RNZAHL_SYSRN" text,
    "RNZAHL_SYSRNZAHL" text,
    "RNZAHL_SYSRNZAHLVER" text,
    "RNZAHL_ZAHLART" text,
    "SYSFIPERIOD" text,
    "SYSVART" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TP" text,
    "UNIQUE_CUSTOM_ID" text,
    "VT_SYSPERSON_OWNER" text,
    "WJ" text
);

-- Table: hist_abs_daily_cash_sweep_buchungen_repurchased
CREATE TABLE "hist_abs_daily_cash_sweep_buchungen_repurchased" (
    "ABS_EFFECTIVE_DATE" text,
    "ABS_END_DATE" text,
    "ABS_FLAG_INACTIVE" text,
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_NAME_OWNER" text,
    "ABS_OFFER_DATE" text,
    "ABS_SETTLEMENT_DATE" text,
    "ABS_STATUS_SPV" text,
    "BEGIN_PERIODE" text,
    "DATUM_FI_BELEG" text,
    "DATUM_FI_CREATE" text,
    "DATUM_FI_GEBUCHT" text,
    "DATUM_FI_VALUTA" text,
    "FI_BETRAG" text,
    "FI_GEGENKONTO" text,
    "FI_GEGENKONTO_BEZ" text,
    "FI_ISINTREL" text,
    "FI_KONTO" text,
    "FI_KONTO_BEZ" text,
    "FI_NEBENKONTO" text,
    "FI_SOLLHABEN" text,
    "FI_STO_RESTORNODATUM" text,
    "FI_STO_RESTORNOFLAG" text,
    "FI_STO_STORNODATUM" text,
    "FI_STO_STORNOFLAG" text,
    "FI_STO_SYSFIORG" text,
    "FI_STO_SYSSTORNO" text,
    "FI_SYSFI" text,
    "FI_SYSFT" text,
    "FI_SYSPERSON" text,
    "FI_SYSVT" text,
    "FI_TEXT" text,
    "FLAG_FJ_PENDING" text,
    "ID_SYSFIJOUR" text,
    "KKL_GEGENKONTO" text,
    "KKL_GEGENKONTO_BEZ" text,
    "KKL_KONTO" text,
    "KKL_KONTO_BEZ" text,
    "KLASSIERUNG_ABS" text,
    "MWST_DIREKTBUCHUNG" text,
    "MWST_SYSMWST" text,
    "PERIODE" text,
    "RNMAHN_SYSRN" text,
    "RNMAHN_SYSRNMAHN" text,
    "RNPOS_SYSRN" text,
    "RNPOS_SYSRNPOS" text,
    "RNZAHL_SYSRN" text,
    "RNZAHL_SYSRNZAHL" text,
    "RNZAHL_SYSRNZAHLVER" text,
    "RNZAHL_ZAHLART" text,
    "SYSFIPERIOD" text,
    "SYSVART" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TP" text,
    "UNIQUE_CUSTOM_ID" text,
    "VT_SYSPERSON_OWNER" text,
    "WJ" text
);

-- Table: hist_abs_daily_cash_sweep_massenbeleg_all
CREATE TABLE "hist_abs_daily_cash_sweep_massenbeleg_all" (
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_STATUS_SPV" text,
    "AFFILIATE_GKONTO" text,
    "AFFILIATE_KONTO" text,
    "BELEGART" text,
    "BELEGDATUM" text,
    "BETRAG" text,
    "BRUTTOBETRAG" text,
    "BUCHUNGSART" text,
    "BUCHUNGSJAHR" text,
    "BUCHUNGSMONAT" text,
    "EINZUG" text,
    "EINZUG_DATUM" text,
    "ESR" text,
    "GEGENKONTO" text,
    "GUTSCHRIFT" text,
    "KONTO" text,
    "KST" text,
    "MASS" text,
    "MWST_CODE" text,
    "OBJEKT" text,
    "PERIODE" text,
    "P_KST" text,
    "RECHNUNGSNUMMER" text,
    "SOLL_HABEN" text,
    "STATUS_SETTLEMENT" text,
    "STEUERBETRAG" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TEXT" text,
    "UNIQUE_CUSTOM_ID_BELEG" text,
    "VALUTADATUM" text,
    "VERTRAG" text,
    "WJ" text,
    "ZAHLUNGSVEREINBARUNG" text,
    "ZINSRELEVANT" text
);

-- Table: hist_abs_daily_cash_sweep_massenbeleg_offer_out
CREATE TABLE "hist_abs_daily_cash_sweep_massenbeleg_offer_out" (
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_STATUS_SPV" text,
    "AFFILIATE_GKONTO" text,
    "AFFILIATE_KONTO" text,
    "BELEGART" text,
    "BELEGDATUM" text,
    "BETRAG" text,
    "BRUTTOBETRAG" text,
    "BUCHUNGSART" text,
    "BUCHUNGSJAHR" text,
    "BUCHUNGSMONAT" text,
    "EINZUG" text,
    "EINZUG_DATUM" text,
    "ESR" text,
    "GEGENKONTO" text,
    "GUTSCHRIFT" text,
    "KONTO" text,
    "KST" text,
    "MASS" text,
    "MWST_CODE" text,
    "OBJEKT" text,
    "PERIODE" text,
    "P_KST" text,
    "RECHNUNGSNUMMER" text,
    "SOLL_HABEN" text,
    "STATUS_SETTLEMENT" text,
    "STEUERBETRAG" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TEXT" text,
    "UNIQUE_CUSTOM_ID_BELEG" text,
    "VALUTADATUM" text,
    "VERTRAG" text,
    "WJ" text,
    "ZAHLUNGSVEREINBARUNG" text,
    "ZINSRELEVANT" text
);

-- Table: hist_abs_daily_cash_sweep_massenbeleg_settled_out
CREATE TABLE "hist_abs_daily_cash_sweep_massenbeleg_settled_out" (
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_STATUS_SPV" text,
    "AFFILIATE_GKONTO" text,
    "AFFILIATE_KONTO" text,
    "BELEGART" text,
    "BELEGDATUM" text,
    "BETRAG" text,
    "BRUTTOBETRAG" text,
    "BUCHUNGSART" text,
    "BUCHUNGSJAHR" text,
    "BUCHUNGSMONAT" text,
    "EINZUG" text,
    "EINZUG_DATUM" text,
    "ESR" text,
    "GEGENKONTO" text,
    "GUTSCHRIFT" text,
    "KONTO" text,
    "KST" text,
    "MASS" text,
    "MWST_CODE" text,
    "OBJEKT" text,
    "PERIODE" text,
    "P_KST" text,
    "RECHNUNGSNUMMER" text,
    "SOLL_HABEN" text,
    "STATUS_SETTLEMENT" text,
    "STEUERBETRAG" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TEXT" text,
    "UNIQUE_CUSTOM_ID_BELEG" text,
    "VALUTADATUM" text,
    "VERTRAG" text,
    "WJ" text,
    "ZAHLUNGSVEREINBARUNG" text,
    "ZINSRELEVANT" text
);

-- Table: hist_abs_daily_transfer_spv_buchungen
CREATE TABLE "hist_abs_daily_transfer_spv_buchungen" (
    "ABS_EFFECTIVE_DATE" text,
    "ABS_END_DATE" text,
    "ABS_FLAG_INACTIVE" text,
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_NAME_OWNER" text,
    "ABS_OFFER_DATE" text,
    "ABS_SETTLEMENT_DATE" text,
    "ABS_STATUS_SPV" text,
    "BEGIN_PERIODE" text,
    "DATUM_FI_BELEG" text,
    "DATUM_FI_CREATE" text,
    "DATUM_FI_GEBUCHT" text,
    "DATUM_FI_VALUTA" text,
    "FI_BETRAG" text,
    "FI_GEGENKONTO" text,
    "FI_GEGENKONTO_BEZ" text,
    "FI_ISINTREL" text,
    "FI_KONTO" text,
    "FI_KONTO_BEZ" text,
    "FI_NEBENKONTO" text,
    "FI_SOLLHABEN" text,
    "FI_STO_RESTORNODATUM" text,
    "FI_STO_RESTORNOFLAG" text,
    "FI_STO_STORNODATUM" text,
    "FI_STO_STORNOFLAG" text,
    "FI_STO_SYSFIORG" text,
    "FI_STO_SYSSTORNO" text,
    "FI_SYSFI" text,
    "FI_SYSFT" text,
    "FI_SYSPERSON" text,
    "FI_SYSVT" text,
    "FI_TEXT" text,
    "FLAG_FJ_PENDING" text,
    "ID_SYSFIJOUR" text,
    "KKL_GEGENKONTO" text,
    "KKL_GEGENKONTO_BEZ" text,
    "KKL_KONTO" text,
    "KKL_KONTO_BEZ" text,
    "KLASSIERUNG_ABS" text,
    "MWST_DIREKTBUCHUNG" text,
    "MWST_SYSMWST" text,
    "PERIODE" text,
    "RNMAHN_SYSRN" text,
    "RNMAHN_SYSRNMAHN" text,
    "RNPOS_SYSRN" text,
    "RNPOS_SYSRNPOS" text,
    "RNZAHL_SYSRN" text,
    "RNZAHL_SYSRNZAHL" text,
    "RNZAHL_SYSRNZAHLVER" text,
    "RNZAHL_ZAHLART" text,
    "SYSFIPERIOD" text,
    "SYSVART" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TP" text,
    "UNIQUE_CUSTOM_ID" text,
    "VT_SYSPERSON_OWNER" text,
    "WJ" text
);

-- Table: hist_abs_daily_transfer_spv_buchungen_repurchased
CREATE TABLE "hist_abs_daily_transfer_spv_buchungen_repurchased" (
    "ABS_EFFECTIVE_DATE" text,
    "ABS_END_DATE" text,
    "ABS_FLAG_INACTIVE" text,
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_NAME_OWNER" text,
    "ABS_OFFER_DATE" text,
    "ABS_SETTLEMENT_DATE" text,
    "ABS_STATUS_SPV" text,
    "BEGIN_PERIODE" text,
    "DATUM_FI_BELEG" text,
    "DATUM_FI_CREATE" text,
    "DATUM_FI_GEBUCHT" text,
    "DATUM_FI_VALUTA" text,
    "FI_BETRAG" text,
    "FI_GEGENKONTO" text,
    "FI_GEGENKONTO_BEZ" text,
    "FI_ISINTREL" text,
    "FI_KONTO" text,
    "FI_KONTO_BEZ" text,
    "FI_NEBENKONTO" text,
    "FI_SOLLHABEN" text,
    "FI_STO_RESTORNODATUM" text,
    "FI_STO_RESTORNOFLAG" text,
    "FI_STO_STORNODATUM" text,
    "FI_STO_STORNOFLAG" text,
    "FI_STO_SYSFIORG" text,
    "FI_STO_SYSSTORNO" text,
    "FI_SYSFI" text,
    "FI_SYSFT" text,
    "FI_SYSPERSON" text,
    "FI_SYSVT" text,
    "FI_TEXT" text,
    "FLAG_FJ_PENDING" text,
    "ID_SYSFIJOUR" text,
    "KKL_GEGENKONTO" text,
    "KKL_GEGENKONTO_BEZ" text,
    "KKL_KONTO" text,
    "KKL_KONTO_BEZ" text,
    "KLASSIERUNG_ABS" text,
    "MWST_DIREKTBUCHUNG" text,
    "MWST_SYSMWST" text,
    "PERIODE" text,
    "RNMAHN_SYSRN" text,
    "RNMAHN_SYSRNMAHN" text,
    "RNPOS_SYSRN" text,
    "RNPOS_SYSRNPOS" text,
    "RNZAHL_SYSRN" text,
    "RNZAHL_SYSRNZAHL" text,
    "RNZAHL_SYSRNZAHLVER" text,
    "RNZAHL_ZAHLART" text,
    "SYSFIPERIOD" text,
    "SYSVART" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TP" text,
    "UNIQUE_CUSTOM_ID" text,
    "VT_SYSPERSON_OWNER" text,
    "WJ" text
);

-- Table: hist_abs_daily_transfer_spv_massenbeleg_all
CREATE TABLE "hist_abs_daily_transfer_spv_massenbeleg_all" (
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_STATUS_SPV" text,
    "AFFILIATE_GKONTO" text,
    "AFFILIATE_KONTO" text,
    "BELEGART" text,
    "BELEGDATUM" text,
    "BETRAG" text,
    "BRUTTOBETRAG" text,
    "BUCHUNGSART" text,
    "BUCHUNGSJAHR" text,
    "BUCHUNGSMONAT" text,
    "EINZUG" text,
    "EINZUG_DATUM" text,
    "ESR" text,
    "GEGENKONTO" text,
    "GUTSCHRIFT" text,
    "KONTO" text,
    "KST" text,
    "MASS" text,
    "MWST_CODE" text,
    "OBJEKT" text,
    "PERIODE" text,
    "P_KST" text,
    "RECHNUNGSNUMMER" text,
    "SOLL_HABEN" text,
    "STATUS_SETTLEMENT" text,
    "STEUERBETRAG" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TEXT" text,
    "UNIQUE_CUSTOM_ID_BELEG" text,
    "VALUTADATUM" text,
    "VERTRAG" text,
    "WJ" text,
    "ZAHLUNGSVEREINBARUNG" text,
    "ZINSRELEVANT" text
);

-- Table: hist_abs_daily_transfer_spv_massenbeleg_offer_out
CREATE TABLE "hist_abs_daily_transfer_spv_massenbeleg_offer_out" (
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_STATUS_SPV" text,
    "AFFILIATE_GKONTO" text,
    "AFFILIATE_KONTO" text,
    "BELEGART" text,
    "BELEGDATUM" text,
    "BETRAG" text,
    "BRUTTOBETRAG" text,
    "BUCHUNGSART" text,
    "BUCHUNGSJAHR" text,
    "BUCHUNGSMONAT" text,
    "EINZUG" text,
    "EINZUG_DATUM" text,
    "ESR" text,
    "GEGENKONTO" text,
    "GUTSCHRIFT" text,
    "KONTO" text,
    "KST" text,
    "MASS" text,
    "MWST_CODE" text,
    "OBJEKT" text,
    "PERIODE" text,
    "P_KST" text,
    "RECHNUNGSNUMMER" text,
    "SOLL_HABEN" text,
    "STATUS_SETTLEMENT" text,
    "STEUERBETRAG" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TEXT" text,
    "UNIQUE_CUSTOM_ID_BELEG" text,
    "VALUTADATUM" text,
    "VERTRAG" text,
    "WJ" text,
    "ZAHLUNGSVEREINBARUNG" text,
    "ZINSRELEVANT" text
);

-- Table: hist_abs_daily_transfer_spv_massenbeleg_settled_out
CREATE TABLE "hist_abs_daily_transfer_spv_massenbeleg_settled_out" (
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_STATUS_SPV" text,
    "AFFILIATE_GKONTO" text,
    "AFFILIATE_KONTO" text,
    "BELEGART" text,
    "BELEGDATUM" text,
    "BETRAG" text,
    "BRUTTOBETRAG" text,
    "BUCHUNGSART" text,
    "BUCHUNGSJAHR" text,
    "BUCHUNGSMONAT" text,
    "EINZUG" text,
    "EINZUG_DATUM" text,
    "ESR" text,
    "GEGENKONTO" text,
    "GUTSCHRIFT" text,
    "KONTO" text,
    "KST" text,
    "MASS" text,
    "MWST_CODE" text,
    "OBJEKT" text,
    "PERIODE" text,
    "P_KST" text,
    "RECHNUNGSNUMMER" text,
    "SOLL_HABEN" text,
    "STATUS_SETTLEMENT" text,
    "STEUERBETRAG" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TEXT" text,
    "UNIQUE_CUSTOM_ID_BELEG" text,
    "VALUTADATUM" text,
    "VERTRAG" text,
    "WJ" text,
    "ZAHLUNGSVEREINBARUNG" text,
    "ZINSRELEVANT" text
);

-- Table: hist_abs_on_duty_recon
CREATE TABLE "hist_abs_on_duty_recon" (
    "ANZAHL_VT" text,
    "ANZAHL_VT_DED" text,
    "EFFECTIVE_BALANCE" text,
    "KONTROLLE_ANZAHL_VT_BALANCE_VIEW" text,
    "KONTROLLE_ANZAHL_VT_BALANCE_VIEW_DED" text,
    "KONTROLLE_ANZAHL_VT_CUR_VIEW" text,
    "KONTROLLE_ANZAHL_VT_CUR_VIEW_DED" text,
    "OUTSTANDING_BALANCE" text,
    "PERIOD_" text,
    "SETTLEMENT_DATE" text,
    "STATUS_SPV" text,
    "SYSPERSON_SPV" text,
    "TARGET_BALANCE" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text
);

-- Table: hist_abs_total_buchungen_abs
CREATE TABLE "hist_abs_total_buchungen_abs" (
    "ABS_EFFECTIVE_DATE" text,
    "ABS_END_DATE" text,
    "ABS_FLAG_INACTIVE" text,
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_NAME_OWNER" text,
    "ABS_OFFER_DATE" text,
    "ABS_SETTLEMENT_DATE" text,
    "ABS_STATUS_SPV" text,
    "BEGIN_PERIODE" text,
    "DATUM_FI_BELEG" text,
    "DATUM_FI_CREATE" text,
    "DATUM_FI_GEBUCHT" text,
    "DATUM_FI_VALUTA" text,
    "FI_BETRAG" text,
    "FI_GEGENKONTO" text,
    "FI_GEGENKONTO_BEZ" text,
    "FI_ISINTREL" text,
    "FI_KONTO" text,
    "FI_KONTO_BEZ" text,
    "FI_NEBENKONTO" text,
    "FI_SOLLHABEN" text,
    "FI_STO_RESTORNODATUM" text,
    "FI_STO_RESTORNOFLAG" text,
    "FI_STO_STORNODATUM" text,
    "FI_STO_STORNOFLAG" text,
    "FI_STO_SYSFIORG" text,
    "FI_STO_SYSSTORNO" text,
    "FI_SYSFI" text,
    "FI_SYSFT" text,
    "FI_SYSPERSON" text,
    "FI_SYSVT" text,
    "FI_TEXT" text,
    "FLAG_FJ_PENDING" text,
    "ID_SYSFIJOUR" text,
    "KKL_GEGENKONTO" text,
    "KKL_GEGENKONTO_BEZ" text,
    "KKL_KONTO" text,
    "KKL_KONTO_BEZ" text,
    "KLASSIERUNG_ABS" text,
    "MWST_DIREKTBUCHUNG" text,
    "MWST_SYSMWST" text,
    "PERIODE" text,
    "RNMAHN_SYSRN" text,
    "RNMAHN_SYSRNMAHN" text,
    "RNPOS_SYSRN" text,
    "RNPOS_SYSRNPOS" text,
    "RNZAHL_SYSRN" text,
    "RNZAHL_SYSRNZAHL" text,
    "RNZAHL_SYSRNZAHLVER" text,
    "RNZAHL_ZAHLART" text,
    "SYSFIPERIOD" text,
    "SYSVART" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TP" text,
    "VT_SYSPERSON_OWNER" text,
    "WJ" text
);

-- Table: hist_cfg_eligibility_criticality
CREATE TABLE "hist_cfg_eligibility_criticality" (
    "BINDING" text,
    "CRITICALITY" text,
    "EL_CRITERIA" text,
    "EL_NAME" text,
    "INSERTED" text,
    "INSERTED_BY" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text
);

-- Table: hist_cfg_spv_values
CREATE TABLE "hist_cfg_spv_values" (
    "SYSPERSON_SPV" text,
    "NAME_SPV" text,
    "REVOLVING_PERIOD_START" text,
    "REVOLVING_PERIOD_END" text,
    "TARGET_BALANCE" text,
    "PRECUT_BALANCE_RED" text,
    "PRECUT_BALANCE_DATE" text,
    "PHASE" text,
    "ACTIVE" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_abs_period_run
CREATE TABLE "hist_eng_abs_period_run" (
    "PERIOD_" text,
    "OPENED_DATE" text,
    "CLOSED_DATE" text,
    "ASSET_BASIS_RUN_EXEC_DATE" text,
    "ASSET_BASIS_RUN_PER_DATE" text,
    "STATUS_" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_abs_run_per_spv_period
CREATE TABLE "hist_eng_abs_run_per_spv_period" (
    "PERIOD_" text,
    "SYSPERSON_SPV" text,
    "RUN_TYPE" text,
    "SELECT_RUN_EXEC_DATE" text,
    "SELL_RUN_EXEC_DATE" text,
    "SETTLEMENT_DATE" text,
    "BALANCE_TARGET" text,
    "REPLENISHMENT_TARGET" text,
    "REPLENISHMENT_ACTUAL" text,
    "ELIG_AT_LEAST_N_INSTALMENTS" text,
    "ELIG_MAX_VEHICLE_WEIGHT" text,
    "ELIG_MAX_OUTSTANDING_BALANCE" text,
    "ELIG_MIN_OUTSTANDING_BALANCE" text,
    "ELIG_MIN_INTEREST_RATE" text,
    "ELIG_MAX_RATIO_RESIDUAL_VALUE" text,
    "ELIG_MIN_MONTHS_UNTIL_TERMINATION" text,
    "ELIG_MIN_LEASE_TERM" text,
    "ELIG_MAX_LEASE_TERM" text,
    "ELIG_MAX_DELINQUENCY_BUCKET" text,
    "ELIG_MIN_CONTRACT_START_DATE" text,
    "ELIG_MAX_RESIDUAL_VALUE" text,
    "ELIG_MAX_FINANCED_AMOUNT_NET" text,
    "ELIG_MIN_DAYS_VEHICLE_REGISTRATION_BEFORE_START_DATE" text,
    "ELIG_MAX_YEARS_VEHICLE_REGISTRATON_BEFORE_START_DATE" text,
    "ELIG_DEALER_OPT_IN_RENEWAL_2021" text,
    "ELIG_DEALER_OPT_IN_OS_2023_1" text,
    "ELIG_DEALER_OPT_IN_OS_2023_2" text,
    "ELIG_NO_USED_CARS" text,
    "ELIG_NO_COMMERCIAL_CARS" text,
    "ELIG_NO_USED_NOR_COMMERCIAL_CARS" text,
    "REPL_MIN_WEIGHTED_AVG_INTEREST_RATE" text,
    "REPL_MAX_USED_CAR_PENETRATION" text,
    "REPL_MAX_COMMERCIAL_CAR_PENETRATION" text,
    "REPL_MAX_COMMERCIAL_USED_CAR_PENETRATION" text,
    "REPL_MAX_MOTO_LCV_PENETRATION" text,
    "REPL_MAX_RESIDUAL_VALUE_PENETRATION" text,
    "REPL_MAX_LARGEST_LESSEE" text,
    "REPL_MAX_LARGEST_RV_DEALER" text,
    "REPL_MAX_LARGEST_CAR_BRAND" text,
    "ELIG_STATUS_RED_POOL" text,
    "ELIG_AT_LEAST_N_INSTALMENTS_RED_POOL" text,
    "ELIG_MAX_VEHICLE_WEIGHT_RED_POOL" text,
    "ELIG_MAX_OUTSTANDING_BALANCE_RED_POOL" text,
    "ELIG_MIN_OUTSTANDING_BALANCE_RED_POOL" text,
    "ELIG_MIN_INTEREST_RATE_RED_POOL" text,
    "ELIG_MAX_RATIO_RESIDUAL_VALUE_RED_POOL" text,
    "ELIG_MIN_MONTHS_UNTIL_TERMINATION_RED_POOL" text,
    "ELIG_MIN_LEASE_TERM_RED_POOL" text,
    "ELIG_MAX_LEASE_TERM_RED_POOL" text,
    "ELIG_MAX_DELINQUENCY_BUCKET_RED_POOL" text,
    "ELIG_MIN_CONTRACT_START_DATE_RED_POOL" text,
    "ELIG_MAX_RESIDUAL_VALUE_RED_POOL" text,
    "ELIG_MAX_FINANCED_AMOUNT_NET_RED_POOL" text,
    "ELIG_MIN_DAYS_VEHICLE_REGISTRATION_BEFORE_START_DATE_RED_POOL" text,
    "ELIG_MAX_YEARS_VEHICLE_REGISTRATON_BEFORE_START_DATE_RED_POOL" text,
    "ELIG_DEALER_OPT_IN_RED_POOL" text,
    "ELIG_DEALER_AGB_CHECK_RED_POOL" text,
    "ELIG_NOT_UMSCHREIBUNG" text,
    "ELIG_RESTWERTVERLAENGERUNG_RV_GREATER_THAN_DEPOSIT" text,
    "MODIFIED" text,
    "MODIFIED_BY_WHOM" text,
    "SHA256" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text,
    "REPL_MAX_DELINQUENCY" text,
    "REPL_MAX_GROSS_WRITE_OFF" text
);

-- Table: hist_eng_eligibility_restrictions_tc
CREATE TABLE "hist_eng_eligibility_restrictions_tc" (
    "PERIOD_" text,
    "SYSPERSON_SPV" text,
    "STRATEGIC_PARTNER" text,
    "MIN_AGB_VERSION_SORTABLE_LEASING" text,
    "MIN_AGB_VERSION_SORTABLE_UMSCHREIBUNG" text,
    "MIN_AGB_VERSION_SORTABLE_RW_VERL" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_id_mapping_person
CREATE TABLE "hist_eng_id_mapping_person" (
    "SYSPERSON" text,
    "ID_BLURRED" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_id_mapping_vt
CREATE TABLE "hist_eng_id_mapping_vt" (
    "SYSVT" text,
    "VT_VERTRAG" text,
    "SYSPERSON_LESSEE" text,
    "CAR_TYP" text,
    "OB_TYP" text,
    "VEHICLE_HAS_ENGINE" text,
    "CAR_BRAND" text,
    "CAR_MODEL" text,
    "RETAIL_PURCHASE_PRICE" text,
    "RESIDUAL_VALUE_NET" text,
    "RESIDUAL_VALUE_INCL_VAT" text,
    "LEASE_TERM" text,
    "AGB_VERSION_SORTABLE" text,
    "PRODUCT_TYPE" text,
    "SUNKEN_SINCE_PERIOD" text,
    "ID_BLURRED" text,
    "PRODUCT_TYPE_" text,
    "AGB_VERSION" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_result_replenishment_criteria_check_v
CREATE TABLE "hist_eng_result_replenishment_criteria_check_v" (
    "SYSPERSON_SPV" text,
    "PERIOD_" text,
    "STATUS_SPV" text,
    "TXT" text,
    "ACTUAL_VALUE" text,
    "CONFIG_VALUE" text,
    "FLG" text,
    "LIMIT_TYPE" text,
    "TAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_servicer_report_result
CREATE TABLE "hist_eng_servicer_report_result" (
    "SYSPERSON_SPV" text,
    "DT" text,
    "PERIOD_" text,
    "TAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_servicer_report_result_defaults
CREATE TABLE "hist_eng_servicer_report_result_defaults" (
    "PRODUCING_MONTH" text,
    "REPORTING_MONTH" text,
    "TOTAL_REPLENISHMENT_AMOUNT_CUMULATIVE" text,
    "NEW_DEFAULTS_IN_MONTH" text,
    "CUMULATIVE_DEFAULTS" text,
    "CUMULATIVE_DEFAULTS_PCT" text,
    "RECOVERIES_IN_MONTH" text,
    "CUMULATIVE_RECOVERIES" text,
    "RECOVERIES_PCT" text,
    "PERIOD_" text,
    "TAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_servicer_report_result_delinquencies
CREATE TABLE "hist_eng_servicer_report_result_delinquencies" (
    "COL_1" text,
    "COL_2" text,
    "COL_3" text,
    "PERIOD_" text,
    "TAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_servicer_report_result_pool_information
CREATE TABLE "hist_eng_servicer_report_result_pool_information" (
    "COL_1" text,
    "COL_2" text,
    "PERIOD_" text,
    "TAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_servicer_report_result_stratification
CREATE TABLE "hist_eng_servicer_report_result_stratification" (
    "TABLE_" text,
    "LEVEL_" text,
    "TEXT" text,
    "TOTAL_OUTSTANDING_BALANCE_CHF" text,
    "TOTAL_OUTSTANDING_BALANCE_PCT" text,
    "TOTAL_RESIDUAL_VALUE_CHF" text,
    "TOTAL_RESIDUAL_VALUE_PCT" text,
    "TOTAL_NUMBER_OF_ASSETS" text,
    "TOTAL_NUMBER_OF_ASSETS_PCT" text,
    "SORT_ORDER" text,
    "PERIOD_" text,
    "TAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_vt_selection_period
CREATE TABLE "hist_eng_vt_selection_period" (
    "PERIOD_" text,
    "SYSVT" text,
    "STATUS_SPV" text,
    "SYSPERSON_SPV" text,
    "SETTLEMENT_DATE" text,
    "OB_BEZEICHNUNG" text,
    "VEHICLE_WEIGHT" text,
    "ENGINE" text,
    "OUTSTANDING_BALANCE" text,
    "BALANCE_OP" text,
    "REPURCHASE_BALANCE" text,
    "DOWNPAYMENT" text,
    "DOWNPAYMENT_EX_VAT" text,
    "FLAG_PPI" text,
    "NOF_SOLL_RATE_BEZAHLT" text,
    "VT_ENDE" text,
    "END_DATE_LEASE_CONTRACT" text,
    "INTEREST_NOMINAL" text,
    "INTEREST_EFFECTIVE" text,
    "SYSPERSON_DEALER" text,
    "DEALER_GROUP_ID" text,
    "DEALER_GROUP_NAME" text,
    "DEALER_OPT_IN_RENEWAL_2021" text,
    "DEALER_OPT_IN_OS_2023_1" text,
    "DEALER_OPT_IN_OS_2023_2" text,
    "DEALER_IS_LESSEE" text,
    "BN_EMPLOYEE" text,
    "CS_EMPLOYEE" text,
    "VT_RESTRUCTURED" text,
    "ZUSTAND_VT" text,
    "ATTRIBUT_VT" text,
    "LESSEE_RESIDENCY" text,
    "CLIENT_TYPE" text,
    "DATE_VEHICLE_REGISTRATION" text,
    "START_DATE_LEASE" text,
    "VT_AUSDATUM" text,
    "DEPOSIT" text,
    "FINANCED_AMOUNT_NET" text,
    "MONTHLY_INSTALMENT" text,
    "CHANNEL_ORIGINATION" text,
    "RISK_CLASS" text,
    "AUSLAUSWEIS" text,
    "MONTHS_ON_BOOK" text,
    "KKG_CONTRACT" text,
    "KANTON" text,
    "RIAN_WB_DELQ" text,
    "WRITE_OFF_AMOUNT" text,
    "CASH_SWEEP_AMOUNT" text,
    "CAR_IS_REPOSSESSED" text,
    "STRATEGIC_PARTNER" text,
    "KM_CONTRACT_START" text,
    "KM_PER_YEAR" text,
    "SHA256" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_vt_selection_period_landing
CREATE TABLE "hist_eng_vt_selection_period_landing" (
    "PERIOD_" text,
    "VT_VERTRAG" text,
    "SYSPERSON_LESSEE" text,
    "SYSVT" text,
    "CAR_TYP" text,
    "OB_BEZEICHNUNG" text,
    "OB_TYP" text,
    "VEHICLE_WEIGHT" text,
    "VEHICLE_HAS_ENGINE" text,
    "ENGINE" text,
    "OUTSTANDING_BALANCE" text,
    "BALANCE_OP" text,
    "DOWNPAYMENT" text,
    "DOWNPAYMENT_EX_VAT" text,
    "FLAG_PPI" text,
    "NOF_SOLL_RATE_BEZAHLT" text,
    "VT_ENDE" text,
    "END_DATE_LEASE_CONTRACT" text,
    "INTEREST_NOMINAL" text,
    "INTEREST_EFFECTIVE" text,
    "SYSPERSON_DEALER" text,
    "DEALER_GROUP_ID" text,
    "DEALER_GROUP_NAME" text,
    "DEALER_OPT_IN_RENEWAL_2021" text,
    "DEALER_OPT_IN_OS_2023_1" text,
    "DEALER_OPT_IN_OS_2023_2" text,
    "DEALER_IS_LESSEE" text,
    "BN_EMPLOYEE" text,
    "CS_EMPLOYEE" text,
    "CAR_BRAND" text,
    "CAR_MODEL" text,
    "RETAIL_PURCHASE_PRICE" text,
    "RESIDUAL_VALUE_NET" text,
    "RESIDUAL_VALUE_INCL_VAT" text,
    "DEFAULT_" text,
    "VT_RESTRUCTURED" text,
    "ZUSTAND_VT" text,
    "ATTRIBUT_VT" text,
    "AGB_VERSION" text,
    "PRODUCT_TYPE_" text,
    "LESSEE_RESIDENCY" text,
    "LEASE_TERM" text,
    "CLIENT_TYPE" text,
    "DATE_VEHICLE_REGISTRATION" text,
    "START_DATE_LEASE" text,
    "VT_AUSDATUM" text,
    "DEPOSIT" text,
    "FINANCED_AMOUNT_NET" text,
    "MONTHLY_INSTALMENT" text,
    "CHANNEL_ORIGINATION" text,
    "RISK_CLASS" text,
    "AUSLAUSWEIS" text,
    "KKG_CONTRACT" text,
    "KANTON" text,
    "RIAN_WB_DELQ" text,
    "WRITE_OFF_AMOUNT" text,
    "CASH_SWEEP_AMOUNT" text,
    "CAR_IS_REPOSSESSED" text,
    "STRATEGIC_PARTNER" text,
    "KM_CONTRACT_START" text,
    "KM_PER_YEAR" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_eng_vt_selection_period_landing_sim
CREATE TABLE "hist_eng_vt_selection_period_landing_sim" (
    "PERIOD_" text,
    "VT_VERTRAG" text,
    "SYSPERSON_LESSEE" text,
    "SYSVT" text,
    "CAR_TYP" text,
    "OB_BEZEICHNUNG" text,
    "OB_TYP" text,
    "VEHICLE_WEIGHT" text,
    "VEHICLE_HAS_ENGINE" text,
    "ENGINE" text,
    "OUTSTANDING_BALANCE" text,
    "BALANCE_OP" text,
    "DOWNPAYMENT" text,
    "DOWNPAYMENT_EX_VAT" text,
    "FLAG_PPI" text,
    "NOF_SOLL_RATE_BEZAHLT" text,
    "VT_ENDE" text,
    "END_DATE_LEASE_CONTRACT" text,
    "INTEREST_NOMINAL" text,
    "INTEREST_EFFECTIVE" text,
    "SYSPERSON_DEALER" text,
    "DEALER_GROUP_ID" text,
    "DEALER_GROUP_NAME" text,
    "DEALER_OPT_IN_RENEWAL_2021" text,
    "DEALER_OPT_IN_OS_2023_1" text,
    "DEALER_OPT_IN_OS_2023_2" text,
    "DEALER_IS_LESSEE" text,
    "BN_EMPLOYEE" text,
    "CS_EMPLOYEE" text,
    "CAR_BRAND" text,
    "CAR_MODEL" text,
    "RETAIL_PURCHASE_PRICE" text,
    "RESIDUAL_VALUE_NET" text,
    "RESIDUAL_VALUE_INCL_VAT" text,
    "DEFAULT_" text,
    "LAST_DEFAULT" text,
    "VT_RESTRUCTURED" text,
    "ZUSTAND_VT" text,
    "ATTRIBUT_VT" text,
    "AGB_VERSION" text,
    "PRODUCT_TYPE_" text,
    "LESSEE_RESIDENCY" text,
    "LEASE_TERM" text,
    "CLIENT_TYPE" text,
    "DATE_VEHICLE_REGISTRATION" text,
    "START_DATE_LEASE" text,
    "VT_AUSDATUM" text,
    "DEPOSIT" text,
    "FINANCED_AMOUNT_NET" text,
    "MONTHLY_INSTALMENT" text,
    "CHANNEL_ORIGINATION" text,
    "RISK_CLASS" text,
    "AUSLAUSWEIS" text,
    "KKG_CONTRACT" text,
    "KANTON" text,
    "RIAN_WB_DELQ" text,
    "WRITE_OFF_AMOUNT" text,
    "CASH_SWEEP_AMOUNT" text,
    "CAR_IS_REPOSSESSED" text,
    "STRATEGIC_PARTNER" text,
    "KM_CONTRACT_START" text,
    "KM_PER_YEAR" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_call_exception
CREATE TABLE "hist_lib_call_exception" (
    "TS" text,
    "ORIGIN_UNIT" text,
    "ORIGIN_LINE" text,
    "ERR_MSG" text,
    "ERR_NR" text,
    "CALL_STACK_ID" text,
    "ID" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_call_exception_stack_error
CREATE TABLE "hist_lib_call_exception_stack_error" (
    "EXCEPTION_ID" text,
    "ERR_MSG" text,
    "ERR_NR" text,
    "ID" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_call_exception_stack_frame
CREATE TABLE "hist_lib_call_exception_stack_frame" (
    "EXCEPTION_ID" text,
    "UNIT" text,
    "LINE" text,
    "ID" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_call_stack
CREATE TABLE "hist_lib_call_stack" (
    "TS" text,
    "ID" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_call_stack_frame
CREATE TABLE "hist_lib_call_stack_frame" (
    "OWNER" text,
    "PACKAGE" text,
    "SUBPROGRAM" text,
    "LINE" text,
    "FLG" text,
    "DEPTH" text,
    "CALL_STACK_ID" text,
    "ID" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_log
CREATE TABLE "hist_lib_log" (
    "TM" text,
    "MSG" text,
    "CALL_STACK" text,
    "NODE" text,
    "ID" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_log_node
CREATE TABLE "hist_lib_log_node" (
    "TM" text,
    "TXT" text,
    "CALL_STACK" text,
    "PARENT_NODE" text,
    "ID" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_log_plsql_block
CREATE TABLE "hist_lib_log_plsql_block" (
    "ID" text,
    "EXCEPTION_ID" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_log_root
CREATE TABLE "hist_lib_log_root" (
    "NODE" text,
    "SES" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_lib_ses
CREATE TABLE "hist_lib_ses" (
    "SID" text,
    "SERIAL#" text,
    "USR" text,
    "USR_PROXY" text,
    "USR_OS" text,
    "TS_EARLIEST_KNOWN" text,
    "TS_LATEST_KNOWN" text,
    "ID" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_meta_abs_daily_cash_sweep_buchungen_repurchased_trace
CREATE TABLE "hist_meta_abs_daily_cash_sweep_buchungen_repurchased_trace" (
    "DATE_PROCESSED" text,
    "FI_KONTO" text,
    "FI_SYSFI" text,
    "ID_SYSFIJOUR" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TP" text,
    "UNIQUE_CUSTOM_ID" text
);

-- Table: hist_meta_abs_daily_cash_sweep_buchungen_trace
CREATE TABLE "hist_meta_abs_daily_cash_sweep_buchungen_trace" (
    "FI_SYSFI" text,
    "ID_SYSFIJOUR" text,
    "FI_KONTO" text,
    "UNIQUE_CUSTOM_ID" text,
    "DATE_PROCESSED" text,
    "TP" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_meta_abs_daily_cash_sweep_massenbeleg_trace
CREATE TABLE "hist_meta_abs_daily_cash_sweep_massenbeleg_trace" (
    "WJ" text,
    "PERIODE" text,
    "ABS_ID_SYSPERSON_OWNER" text,
    "BETRAG" text,
    "BELEGART" text,
    "BELEGDATUM" text,
    "VALUTADATUM" text,
    "BRUTTOBETRAG" text,
    "SOLL_HABEN" text,
    "KONTO" text,
    "GEGENKONTO" text,
    "ABS_STATUS_SPV" text,
    "STATUS_SETTLEMENT" text,
    "UNIQUE_CUSTOM_ID_BELEG" text,
    "DATE_PROCESSED" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_meta_abs_daily_transfer_spv_buchungen_repurchased_trace
CREATE TABLE "hist_meta_abs_daily_transfer_spv_buchungen_repurchased_trace" (
    "DATE_PROCESSED" text,
    "FI_KONTO" text,
    "FI_SYSFI" text,
    "ID_SYSFIJOUR" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TP" text,
    "UNIQUE_CUSTOM_ID" text
);

-- Table: hist_meta_abs_daily_transfer_spv_buchungen_trace
CREATE TABLE "hist_meta_abs_daily_transfer_spv_buchungen_trace" (
    "FI_SYSFI" text,
    "ID_SYSFIJOUR" text,
    "FI_KONTO" text,
    "UNIQUE_CUSTOM_ID" text,
    "DATE_PROCESSED" text,
    "TP" text,
    "TECH_LOAD_DATE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text
);

-- Table: hist_meta_abs_daily_transfer_spv_massenbeleg_trace
CREATE TABLE "hist_meta_abs_daily_transfer_spv_massenbeleg_trace" (
    "WJ" text,
    "PERIODE" text,
    "ABS_ID_SYSPERSON_OWNER" text,
    "BETRAG" text,
    "BELEGART" text,
    "BELEGDATUM" text,
    "VALUTADATUM" text,
    "BRUTTOBETRAG" text,
    "SOLL_HABEN" text,
    "KONTO" text,
    "GEGENKONTO" text,
    "ABS_STATUS_SPV" text,
    "STATUS_SETTLEMENT" text,
    "UNIQUE_CUSTOM_ID_BELEG" text,
    "DATE_PROCESSED" text,
    "TECH_LOAD_DATE" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_VALID_TO" text,
    "TECH_VALID_FROM" text,
    "TECH_RUNID_CREATE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RECORD_TYPE" text,
    "TECH_PK" text,
    "TECH_MODIFICATION_DATE" text
);

-- Table: hist_mon_base_abs_el
CREATE TABLE "hist_mon_base_abs_el" (
    "ABS_EFFECTIVE_DATE" text,
    "ABS_END_DATE" text,
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_INACTIVE" text,
    "ABS_NAME_SPV" text,
    "ABS_OFFER_DATE" text,
    "ABS_SETTLEMENT_DATE" text,
    "ABS_STATUS_SPV" text,
    "ABS_SYSPERSON_DEALER" text,
    "ABS_SYSPERSON_LESSEE" text,
    "ANTOB_BEZEICHNUNG" text,
    "ANTRAG_ERFASSUNG" text,
    "ANTRIEB" text,
    "ANZ_PAYMENTS" text,
    "AUSLAUSWEIS" text,
    "BESTAND" text,
    "BL_DEALER_REASON" text,
    "BL_VT_REASON" text,
    "CURRENT_PERIOD" text,
    "DATE_TODAY_SYS" text,
    "DAYDIFF_ERSTZUL_VTBEGINN" text,
    "DELQ" text,
    "EFFECTIVE_BALANCE" text,
    "EL_AGB_ERFASSUNG" text,
    "EL_AGB_VERSION" text,
    "EL_ANTOB_FZENGINE_KW" text,
    "EL_ANTOB_FZENGINE_TREIBSTOFF" text,
    "EL_ANZ_PAYMENTS" text,
    "EL_BLACKLIST_DEALER" text,
    "EL_BLACKLIST_VT" text,
    "EL_BRAND" text,
    "EL_BRAND_DESC" text,
    "EL_CHANGEDVTENDE" text,
    "EL_COND_MA_CSG" text,
    "EL_COND_MA_NEU" text,
    "EL_DEALER_OPTIN" text,
    "EL_DELQ" text,
    "EL_EMPLOYEE_CS_ALT" text,
    "EL_EXTRATCODE" text,
    "EL_EXTRATCODE_DESC" text,
    "EL_FZGEW" text,
    "EL_FZLEERGEW" text,
    "EL_FZTYP" text,
    "EL_FZTYP_DESC" text,
    "EL_FZZULGEW" text,
    "EL_KD_EQ_HD" text,
    "EL_KD_EQ_HDVK" text,
    "EL_KD_EQ_HDVK_IDENTEG" text,
    "EL_KD_EQ_HD_IDENTEG" text,
    "EL_MAXVTNETFINAMOUNT" text,
    "EL_MAXVTRELRW" text,
    "EL_MAXVTRW" text,
    "EL_MAX_RKL" text,
    "EL_MINDIFFVTENDE" text,
    "EL_MINVTBEGINN" text,
    "EL_MINVTZINSEFF" text,
    "EL_OB_FZENGINE_BEZ" text,
    "EL_OB_REGDATE_144MONTHS" text,
    "EL_OB_REGDATE_45DAYS" text,
    "EL_PERMIT" text,
    "EL_PKZ_EMPLOYEE_BN" text,
    "EL_PKZ_EMPLOYEE_CS" text,
    "EL_RESIDENCY_CH" text,
    "EL_VART" text,
    "EL_VART_DESC" text,
    "EL_VTGLZ_6" text,
    "EL_VTGLZ_60" text,
    "EL_VTHISTZUSTATTR" text,
    "EL_VTTYP" text,
    "EL_VTTYP_DESC" text,
    "EL_VTZUSTATTR" text,
    "EL_VT_SALDO_200K" text,
    "EL_VT_SALDO_5K" text,
    "ERSTZUL" text,
    "EXTRATINGCODE" text,
    "FZTYP" text,
    "IDENTEG_HD" text,
    "IDENTEG_KD" text,
    "IDENTEG_VK" text,
    "IS_BLACKLISTED" text,
    "IS_DEFLAGGED" text,
    "KW" text,
    "LAST_EXISTING_PERIOD" text,
    "LEERGEW" text,
    "LIST_ROLEATTRIB_NAME" text,
    "MIN_RELEVANT_PERIOD" text,
    "MITARBEITERFLAG" text,
    "MONDIFF_ERSTZUL_VTBEGINN" text,
    "MONDIFF_VTENDE" text,
    "MOTOR" text,
    "NATIONALITAET_ISO" text,
    "NATIONALITAET_NAME" text,
    "OBJEKTART" text,
    "OB_BEZEICHNUNG" text,
    "OB_HERSTELLER" text,
    "PERSON_COMMERCIALFLAG" text,
    "PRIVATFLAG" text,
    "PRODCONDITION_MA" text,
    "PRODCONDNAME" text,
    "RKL_MAX" text,
    "SYSANTRAG" text,
    "SYSBRAND" text,
    "SYSLAND" text,
    "SYSPRPRODUCT" text,
    "SYSVART" text,
    "SYSVTTYP" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "TREIBSTOFF" text,
    "VTATTRIBUT" text,
    "VTBEGINN" text,
    "VTBGEXTERN" text,
    "VTDATABSCHLUSS" text,
    "VTENDE" text,
    "VTGLZ" text,
    "VTHISTATTRIBUT" text,
    "VTHISTZUSTAND" text,
    "VTNETFINAMOUNT" text,
    "VTOBHD_SYSHD" text,
    "VTRELRW" text,
    "VTRW" text,
    "VTSZ" text,
    "VTZINSEFF" text,
    "VTZUSTAND" text,
    "VT_AGB_VERSION" text,
    "VT_AGB_VERSION_RAW" text,
    "VT_SYSID" text,
    "VT_SYSKD" text,
    "VT_SYSVK" text,
    "VT_VERTRAG" text,
    "WOHNSITZLAND_ISO" text,
    "WOHNSITZLAND_NAME" text,
    "ZULGEW" text,
    "DEPOSIT" text,
    "RESIDUAL_VALUE_NET" text,
    "PRODUKTART" text,
    "EL_VT_SALDO_150K" text,
    "EL_MINVTZINSEFF_2" text,
    "EL_BRAND_SPV2" text,
    "EL_AGB_VERSION_SPV2" text,
    "EL_AGB_ERFASSUNG_SPV2" text,
    "EFFECTIVE_INTEREST" text,
    "REPORTING_INCLUDE_FOR_RV" text
);

-- Table: hist_mon_el_calc
CREATE TABLE "hist_mon_el_calc" (
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_INACTIVE" text,
    "ABS_NAME_SPV" text,
    "ABS_STATUS_SPV" text,
    "CURRENT_PERIOD" text,
    "EL_001" text,
    "EL_002" text,
    "EL_003" text,
    "EL_004" text,
    "EL_005" text,
    "EL_006_SPV1" text,
    "EL_006_SPV2" text,
    "EL_007" text,
    "EL_008" text,
    "EL_009" text,
    "EL_010" text,
    "EL_011" text,
    "EL_012" text,
    "EL_013" text,
    "EL_014_SPV1" text,
    "EL_014_SPV2" text,
    "EL_015" text,
    "EL_016" text,
    "EL_017" text,
    "EL_018" text,
    "EL_019" text,
    "EL_020" text,
    "EL_021" text,
    "EL_022" text,
    "EL_023" text,
    "EL_024_SPV1" text,
    "EL_024_SPV2" text,
    "EL_025_1_SPV1" text,
    "EL_025_1_SPV2" text,
    "EL_025_2_SPV1" text,
    "EL_025_2_SPV2" text,
    "EL_026" text,
    "EL_027" text,
    "EL_028" text,
    "EL_029" text,
    "EL_030" text,
    "EL_031" text,
    "EL_032" text,
    "EL_033" text,
    "EL_034" text,
    "EL_035" text,
    "EL_ALL_OK_SPV1" text,
    "EL_ALL_OK_SPV2" text,
    "EL_COUNT_SPV1" text,
    "EL_COUNT_SPV2" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text,
    "VT_SYSID" text,
    "VT_VERTRAG" text
);

-- Table: hist_mon_rp_calc
CREATE TABLE "hist_mon_rp_calc" (
    "ABS_ID_SYSPERSON_OWNER" text,
    "ABS_INACTIVE" text,
    "ABS_NAME_SPV" text,
    "ABS_STATUS_SPV" text,
    "CURRENT_PERIOD" text,
    "RP_CRITERIA" text,
    "RP_JUSTIFICATION" text,
    "RP_LIMIT_UTILIZATION" text,
    "RP_NAME" text,
    "STATUS_OK_NOK" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text
);

-- Table: hist_placeholder
CREATE TABLE "hist_placeholder" (
    "PLACEHOLDER" text,
    "TECH_BK" text,
    "TECH_CURRENT_FLAG" text,
    "TECH_LOAD_DATE" text,
    "TECH_MODIFICATION_DATE" text,
    "TECH_PK" text,
    "TECH_RECORD_TYPE" text,
    "TECH_RUNID_CLOSE" text,
    "TECH_RUNID_CREATE" text,
    "TECH_VALID_FROM" text,
    "TECH_VALID_TO" text
);

-- Table: meta_abs_processing_status
CREATE TABLE "meta_abs_processing_status" (
    "EXECUTION_GROUP" text,
    "ORDER_DATE" text,
    "STATUS" text,
    "LOG_RUN_ID" text,
    "MESSAGE" text,
    "JOB_NAME" text,
    "META_ABS_PROCESSING_STATUS_ID" text,
    "TECH_LOAD_DATE" text
);

-- Table: meta_execution_groups_config
CREATE TABLE "meta_execution_groups_config" (
    "EXECUTION_GROUP" text,
    "SCHEDULING_TYPE" text,
    "EXECUTION_ORDER" text,
    "TECH_LOAD_DATE" text
);

