-- Table: hist_abs_daily_buchungen_abs
CREATE TABLE "hist_abs_daily_buchungen_abs" (
    "abs_effective_date" text,
    "abs_end_date" text,
    "abs_flag_inactive" text,
    "abs_id_sysperson_owner" text,
    "abs_name_owner" text,
    "abs_offer_date" text,
    "abs_settlement_date" text,
    "abs_status_spv" text,
    "begin_periode" text,
    "datum_fi_beleg" text,
    "datum_fi_create" text,
    "datum_fi_gebucht" text,
    "datum_fi_valuta" text,
    "fi_betrag" text,
    "fi_gegenkonto" text,
    "fi_gegenkonto_bez" text,
    "fi_isintrel" text,
    "fi_konto" text,
    "fi_konto_bez" text,
    "fi_nebenkonto" text,
    "fi_sollhaben" text,
    "fi_sto_restornodatum" text,
    "fi_sto_restornoflag" text,
    "fi_sto_stornodatum" text,
    "fi_sto_stornoflag" text,
    "fi_sto_sysfiorg" text,
    "fi_sto_sysstorno" text,
    "fi_sysfi" text,
    "fi_sysft" text,
    "fi_sysperson" text,
    "fi_sysvt" text,
    "fi_text" text,
    "flag_fj_pending" text,
    "id_sysfijour" text,
    "kkl_gegenkonto" text,
    "kkl_gegenkonto_bez" text,
    "kkl_konto" text,
    "kkl_konto_bez" text,
    "klassierung_abs" text,
    "mwst_direktbuchung" text,
    "mwst_sysmwst" text,
    "periode" text,
    "rnmahn_sysrn" text,
    "rnmahn_sysrnmahn" text,
    "rnpos_sysrn" text,
    "rnpos_sysrnpos" text,
    "rnzahl_sysrn" text,
    "rnzahl_sysrnzahl" text,
    "rnzahl_sysrnzahlver" text,
    "rnzahl_zahlart" text,
    "sysfiperiod" text,
    "sysvart" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "tp" text,
    "vt_sysperson_owner" text,
    "wj" text
);

-- Table: hist_abs_daily_cash_sweep_buchungen
CREATE TABLE "hist_abs_daily_cash_sweep_buchungen" (
    "abs_effective_date" text,
    "abs_end_date" text,
    "abs_flag_inactive" text,
    "abs_id_sysperson_owner" text,
    "abs_name_owner" text,
    "abs_offer_date" text,
    "abs_settlement_date" text,
    "abs_status_spv" text,
    "begin_periode" text,
    "datum_fi_beleg" text,
    "datum_fi_create" text,
    "datum_fi_gebucht" text,
    "datum_fi_valuta" text,
    "fi_betrag" text,
    "fi_gegenkonto" text,
    "fi_gegenkonto_bez" text,
    "fi_isintrel" text,
    "fi_konto" text,
    "fi_konto_bez" text,
    "fi_nebenkonto" text,
    "fi_sollhaben" text,
    "fi_sto_restornodatum" text,
    "fi_sto_restornoflag" text,
    "fi_sto_stornodatum" text,
    "fi_sto_stornoflag" text,
    "fi_sto_sysfiorg" text,
    "fi_sto_sysstorno" text,
    "fi_sysfi" text,
    "fi_sysft" text,
    "fi_sysperson" text,
    "fi_sysvt" text,
    "fi_text" text,
    "flag_fj_pending" text,
    "id_sysfijour" text,
    "kkl_gegenkonto" text,
    "kkl_gegenkonto_bez" text,
    "kkl_konto" text,
    "kkl_konto_bez" text,
    "klassierung_abs" text,
    "mwst_direktbuchung" text,
    "mwst_sysmwst" text,
    "periode" text,
    "rnmahn_sysrn" text,
    "rnmahn_sysrnmahn" text,
    "rnpos_sysrn" text,
    "rnpos_sysrnpos" text,
    "rnzahl_sysrn" text,
    "rnzahl_sysrnzahl" text,
    "rnzahl_sysrnzahlver" text,
    "rnzahl_zahlart" text,
    "sysfiperiod" text,
    "sysvart" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "tp" text,
    "unique_custom_id" text,
    "vt_sysperson_owner" text,
    "wj" text
);

-- Table: hist_abs_daily_cash_sweep_buchungen_repurchased
CREATE TABLE "hist_abs_daily_cash_sweep_buchungen_repurchased" (
    "abs_effective_date" text,
    "abs_end_date" text,
    "abs_flag_inactive" text,
    "abs_id_sysperson_owner" text,
    "abs_name_owner" text,
    "abs_offer_date" text,
    "abs_settlement_date" text,
    "abs_status_spv" text,
    "begin_periode" text,
    "datum_fi_beleg" text,
    "datum_fi_create" text,
    "datum_fi_gebucht" text,
    "datum_fi_valuta" text,
    "fi_betrag" text,
    "fi_gegenkonto" text,
    "fi_gegenkonto_bez" text,
    "fi_isintrel" text,
    "fi_konto" text,
    "fi_konto_bez" text,
    "fi_nebenkonto" text,
    "fi_sollhaben" text,
    "fi_sto_restornodatum" text,
    "fi_sto_restornoflag" text,
    "fi_sto_stornodatum" text,
    "fi_sto_stornoflag" text,
    "fi_sto_sysfiorg" text,
    "fi_sto_sysstorno" text,
    "fi_sysfi" text,
    "fi_sysft" text,
    "fi_sysperson" text,
    "fi_sysvt" text,
    "fi_text" text,
    "flag_fj_pending" text,
    "id_sysfijour" text,
    "kkl_gegenkonto" text,
    "kkl_gegenkonto_bez" text,
    "kkl_konto" text,
    "kkl_konto_bez" text,
    "klassierung_abs" text,
    "mwst_direktbuchung" text,
    "mwst_sysmwst" text,
    "periode" text,
    "rnmahn_sysrn" text,
    "rnmahn_sysrnmahn" text,
    "rnpos_sysrn" text,
    "rnpos_sysrnpos" text,
    "rnzahl_sysrn" text,
    "rnzahl_sysrnzahl" text,
    "rnzahl_sysrnzahlver" text,
    "rnzahl_zahlart" text,
    "sysfiperiod" text,
    "sysvart" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "tp" text,
    "unique_custom_id" text,
    "vt_sysperson_owner" text,
    "wj" text
);

-- Table: hist_abs_daily_cash_sweep_massenbeleg_all
CREATE TABLE "hist_abs_daily_cash_sweep_massenbeleg_all" (
    "abs_id_sysperson_owner" text,
    "abs_status_spv" text,
    "affiliate_gkonto" text,
    "affiliate_konto" text,
    "belegart" text,
    "belegdatum" text,
    "betrag" text,
    "bruttobetrag" text,
    "buchungsart" text,
    "buchungsjahr" text,
    "buchungsmonat" text,
    "einzug" text,
    "einzug_datum" text,
    "esr" text,
    "gegenkonto" text,
    "gutschrift" text,
    "konto" text,
    "kst" text,
    "mass" text,
    "mwst_code" text,
    "objekt" text,
    "periode" text,
    "p_kst" text,
    "rechnungsnummer" text,
    "soll_haben" text,
    "status_settlement" text,
    "steuerbetrag" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "text" text,
    "unique_custom_id_beleg" text,
    "valutadatum" text,
    "vertrag" text,
    "wj" text,
    "zahlungsvereinbarung" text,
    "zinsrelevant" text
);

-- Table: hist_abs_daily_cash_sweep_massenbeleg_offer_out
CREATE TABLE "hist_abs_daily_cash_sweep_massenbeleg_offer_out" (
    "abs_id_sysperson_owner" text,
    "abs_status_spv" text,
    "affiliate_gkonto" text,
    "affiliate_konto" text,
    "belegart" text,
    "belegdatum" text,
    "betrag" text,
    "bruttobetrag" text,
    "buchungsart" text,
    "buchungsjahr" text,
    "buchungsmonat" text,
    "einzug" text,
    "einzug_datum" text,
    "esr" text,
    "gegenkonto" text,
    "gutschrift" text,
    "konto" text,
    "kst" text,
    "mass" text,
    "mwst_code" text,
    "objekt" text,
    "periode" text,
    "p_kst" text,
    "rechnungsnummer" text,
    "soll_haben" text,
    "status_settlement" text,
    "steuerbetrag" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "text" text,
    "unique_custom_id_beleg" text,
    "valutadatum" text,
    "vertrag" text,
    "wj" text,
    "zahlungsvereinbarung" text,
    "zinsrelevant" text
);

-- Table: hist_abs_daily_cash_sweep_massenbeleg_settled_out
CREATE TABLE "hist_abs_daily_cash_sweep_massenbeleg_settled_out" (
    "abs_id_sysperson_owner" text,
    "abs_status_spv" text,
    "affiliate_gkonto" text,
    "affiliate_konto" text,
    "belegart" text,
    "belegdatum" text,
    "betrag" text,
    "bruttobetrag" text,
    "buchungsart" text,
    "buchungsjahr" text,
    "buchungsmonat" text,
    "einzug" text,
    "einzug_datum" text,
    "esr" text,
    "gegenkonto" text,
    "gutschrift" text,
    "konto" text,
    "kst" text,
    "mass" text,
    "mwst_code" text,
    "objekt" text,
    "periode" text,
    "p_kst" text,
    "rechnungsnummer" text,
    "soll_haben" text,
    "status_settlement" text,
    "steuerbetrag" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "text" text,
    "unique_custom_id_beleg" text,
    "valutadatum" text,
    "vertrag" text,
    "wj" text,
    "zahlungsvereinbarung" text,
    "zinsrelevant" text
);

-- Table: hist_abs_daily_transfer_spv_buchungen
CREATE TABLE "hist_abs_daily_transfer_spv_buchungen" (
    "abs_effective_date" text,
    "abs_end_date" text,
    "abs_flag_inactive" text,
    "abs_id_sysperson_owner" text,
    "abs_name_owner" text,
    "abs_offer_date" text,
    "abs_settlement_date" text,
    "abs_status_spv" text,
    "begin_periode" text,
    "datum_fi_beleg" text,
    "datum_fi_create" text,
    "datum_fi_gebucht" text,
    "datum_fi_valuta" text,
    "fi_betrag" text,
    "fi_gegenkonto" text,
    "fi_gegenkonto_bez" text,
    "fi_isintrel" text,
    "fi_konto" text,
    "fi_konto_bez" text,
    "fi_nebenkonto" text,
    "fi_sollhaben" text,
    "fi_sto_restornodatum" text,
    "fi_sto_restornoflag" text,
    "fi_sto_stornodatum" text,
    "fi_sto_stornoflag" text,
    "fi_sto_sysfiorg" text,
    "fi_sto_sysstorno" text,
    "fi_sysfi" text,
    "fi_sysft" text,
    "fi_sysperson" text,
    "fi_sysvt" text,
    "fi_text" text,
    "flag_fj_pending" text,
    "id_sysfijour" text,
    "kkl_gegenkonto" text,
    "kkl_gegenkonto_bez" text,
    "kkl_konto" text,
    "kkl_konto_bez" text,
    "klassierung_abs" text,
    "mwst_direktbuchung" text,
    "mwst_sysmwst" text,
    "periode" text,
    "rnmahn_sysrn" text,
    "rnmahn_sysrnmahn" text,
    "rnpos_sysrn" text,
    "rnpos_sysrnpos" text,
    "rnzahl_sysrn" text,
    "rnzahl_sysrnzahl" text,
    "rnzahl_sysrnzahlver" text,
    "rnzahl_zahlart" text,
    "sysfiperiod" text,
    "sysvart" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "tp" text,
    "unique_custom_id" text,
    "vt_sysperson_owner" text,
    "wj" text
);

-- Table: hist_abs_daily_transfer_spv_buchungen_repurchased
CREATE TABLE "hist_abs_daily_transfer_spv_buchungen_repurchased" (
    "abs_effective_date" text,
    "abs_end_date" text,
    "abs_flag_inactive" text,
    "abs_id_sysperson_owner" text,
    "abs_name_owner" text,
    "abs_offer_date" text,
    "abs_settlement_date" text,
    "abs_status_spv" text,
    "begin_periode" text,
    "datum_fi_beleg" text,
    "datum_fi_create" text,
    "datum_fi_gebucht" text,
    "datum_fi_valuta" text,
    "fi_betrag" text,
    "fi_gegenkonto" text,
    "fi_gegenkonto_bez" text,
    "fi_isintrel" text,
    "fi_konto" text,
    "fi_konto_bez" text,
    "fi_nebenkonto" text,
    "fi_sollhaben" text,
    "fi_sto_restornodatum" text,
    "fi_sto_restornoflag" text,
    "fi_sto_stornodatum" text,
    "fi_sto_stornoflag" text,
    "fi_sto_sysfiorg" text,
    "fi_sto_sysstorno" text,
    "fi_sysfi" text,
    "fi_sysft" text,
    "fi_sysperson" text,
    "fi_sysvt" text,
    "fi_text" text,
    "flag_fj_pending" text,
    "id_sysfijour" text,
    "kkl_gegenkonto" text,
    "kkl_gegenkonto_bez" text,
    "kkl_konto" text,
    "kkl_konto_bez" text,
    "klassierung_abs" text,
    "mwst_direktbuchung" text,
    "mwst_sysmwst" text,
    "periode" text,
    "rnmahn_sysrn" text,
    "rnmahn_sysrnmahn" text,
    "rnpos_sysrn" text,
    "rnpos_sysrnpos" text,
    "rnzahl_sysrn" text,
    "rnzahl_sysrnzahl" text,
    "rnzahl_sysrnzahlver" text,
    "rnzahl_zahlart" text,
    "sysfiperiod" text,
    "sysvart" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "tp" text,
    "unique_custom_id" text,
    "vt_sysperson_owner" text,
    "wj" text
);

-- Table: hist_abs_daily_transfer_spv_massenbeleg_all
CREATE TABLE "hist_abs_daily_transfer_spv_massenbeleg_all" (
    "abs_id_sysperson_owner" text,
    "abs_status_spv" text,
    "affiliate_gkonto" text,
    "affiliate_konto" text,
    "belegart" text,
    "belegdatum" text,
    "betrag" text,
    "bruttobetrag" text,
    "buchungsart" text,
    "buchungsjahr" text,
    "buchungsmonat" text,
    "einzug" text,
    "einzug_datum" text,
    "esr" text,
    "gegenkonto" text,
    "gutschrift" text,
    "konto" text,
    "kst" text,
    "mass" text,
    "mwst_code" text,
    "objekt" text,
    "periode" text,
    "p_kst" text,
    "rechnungsnummer" text,
    "soll_haben" text,
    "status_settlement" text,
    "steuerbetrag" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "text" text,
    "unique_custom_id_beleg" text,
    "valutadatum" text,
    "vertrag" text,
    "wj" text,
    "zahlungsvereinbarung" text,
    "zinsrelevant" text
);

-- Table: hist_abs_daily_transfer_spv_massenbeleg_offer_out
CREATE TABLE "hist_abs_daily_transfer_spv_massenbeleg_offer_out" (
    "abs_id_sysperson_owner" text,
    "abs_status_spv" text,
    "affiliate_gkonto" text,
    "affiliate_konto" text,
    "belegart" text,
    "belegdatum" text,
    "betrag" text,
    "bruttobetrag" text,
    "buchungsart" text,
    "buchungsjahr" text,
    "buchungsmonat" text,
    "einzug" text,
    "einzug_datum" text,
    "esr" text,
    "gegenkonto" text,
    "gutschrift" text,
    "konto" text,
    "kst" text,
    "mass" text,
    "mwst_code" text,
    "objekt" text,
    "periode" text,
    "p_kst" text,
    "rechnungsnummer" text,
    "soll_haben" text,
    "status_settlement" text,
    "steuerbetrag" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "text" text,
    "unique_custom_id_beleg" text,
    "valutadatum" text,
    "vertrag" text,
    "wj" text,
    "zahlungsvereinbarung" text,
    "zinsrelevant" text
);

-- Table: hist_abs_daily_transfer_spv_massenbeleg_settled_out
CREATE TABLE "hist_abs_daily_transfer_spv_massenbeleg_settled_out" (
    "abs_id_sysperson_owner" text,
    "abs_status_spv" text,
    "affiliate_gkonto" text,
    "affiliate_konto" text,
    "belegart" text,
    "belegdatum" text,
    "betrag" text,
    "bruttobetrag" text,
    "buchungsart" text,
    "buchungsjahr" text,
    "buchungsmonat" text,
    "einzug" text,
    "einzug_datum" text,
    "esr" text,
    "gegenkonto" text,
    "gutschrift" text,
    "konto" text,
    "kst" text,
    "mass" text,
    "mwst_code" text,
    "objekt" text,
    "periode" text,
    "p_kst" text,
    "rechnungsnummer" text,
    "soll_haben" text,
    "status_settlement" text,
    "steuerbetrag" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "text" text,
    "unique_custom_id_beleg" text,
    "valutadatum" text,
    "vertrag" text,
    "wj" text,
    "zahlungsvereinbarung" text,
    "zinsrelevant" text
);

-- Table: hist_abs_on_duty_recon
CREATE TABLE "hist_abs_on_duty_recon" (
    "anzahl_vt" text,
    "anzahl_vt_ded" text,
    "effective_balance" text,
    "kontrolle_anzahl_vt_balance_view" text,
    "kontrolle_anzahl_vt_balance_view_ded" text,
    "kontrolle_anzahl_vt_cur_view" text,
    "kontrolle_anzahl_vt_cur_view_ded" text,
    "outstanding_balance" text,
    "period_" text,
    "settlement_date" text,
    "status_spv" text,
    "sysperson_spv" text,
    "target_balance" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text
);

-- Table: hist_abs_total_buchungen_abs
CREATE TABLE "hist_abs_total_buchungen_abs" (
    "abs_effective_date" text,
    "abs_end_date" text,
    "abs_flag_inactive" text,
    "abs_id_sysperson_owner" text,
    "abs_name_owner" text,
    "abs_offer_date" text,
    "abs_settlement_date" text,
    "abs_status_spv" text,
    "begin_periode" text,
    "datum_fi_beleg" text,
    "datum_fi_create" text,
    "datum_fi_gebucht" text,
    "datum_fi_valuta" text,
    "fi_betrag" text,
    "fi_gegenkonto" text,
    "fi_gegenkonto_bez" text,
    "fi_isintrel" text,
    "fi_konto" text,
    "fi_konto_bez" text,
    "fi_nebenkonto" text,
    "fi_sollhaben" text,
    "fi_sto_restornodatum" text,
    "fi_sto_restornoflag" text,
    "fi_sto_stornodatum" text,
    "fi_sto_stornoflag" text,
    "fi_sto_sysfiorg" text,
    "fi_sto_sysstorno" text,
    "fi_sysfi" text,
    "fi_sysft" text,
    "fi_sysperson" text,
    "fi_sysvt" text,
    "fi_text" text,
    "flag_fj_pending" text,
    "id_sysfijour" text,
    "kkl_gegenkonto" text,
    "kkl_gegenkonto_bez" text,
    "kkl_konto" text,
    "kkl_konto_bez" text,
    "klassierung_abs" text,
    "mwst_direktbuchung" text,
    "mwst_sysmwst" text,
    "periode" text,
    "rnmahn_sysrn" text,
    "rnmahn_sysrnmahn" text,
    "rnpos_sysrn" text,
    "rnpos_sysrnpos" text,
    "rnzahl_sysrn" text,
    "rnzahl_sysrnzahl" text,
    "rnzahl_sysrnzahlver" text,
    "rnzahl_zahlart" text,
    "sysfiperiod" text,
    "sysvart" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "tp" text,
    "vt_sysperson_owner" text,
    "wj" text
);

-- Table: hist_cfg_eligibility_criticality
CREATE TABLE "hist_cfg_eligibility_criticality" (
    "binding" text,
    "criticality" text,
    "el_criteria" text,
    "el_name" text,
    "inserted" text,
    "inserted_by" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text
);

-- Table: hist_cfg_spv_values
CREATE TABLE "hist_cfg_spv_values" (
    "sysperson_spv" text,
    "name_spv" text,
    "revolving_period_start" text,
    "revolving_period_end" text,
    "target_balance" text,
    "precut_balance_red" text,
    "precut_balance_date" text,
    "phase" text,
    "active" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_abs_period_run
CREATE TABLE "hist_eng_abs_period_run" (
    "period_" text,
    "opened_date" text,
    "closed_date" text,
    "asset_basis_run_exec_date" text,
    "asset_basis_run_per_date" text,
    "status_" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_abs_run_per_spv_period
CREATE TABLE "hist_eng_abs_run_per_spv_period" (
    "period_" text,
    "sysperson_spv" text,
    "run_type" text,
    "select_run_exec_date" text,
    "sell_run_exec_date" text,
    "settlement_date" text,
    "balance_target" text,
    "replenishment_target" text,
    "replenishment_actual" text,
    "elig_at_least_n_instalments" text,
    "elig_max_vehicle_weight" text,
    "elig_max_outstanding_balance" text,
    "elig_min_outstanding_balance" text,
    "elig_min_interest_rate" text,
    "elig_max_ratio_residual_value" text,
    "elig_min_months_until_termination" text,
    "elig_min_lease_term" text,
    "elig_max_lease_term" text,
    "elig_max_delinquency_bucket" text,
    "elig_min_contract_start_date" text,
    "elig_max_residual_value" text,
    "elig_max_financed_amount_net" text,
    "elig_min_days_vehicle_registration_before_start_date" text,
    "elig_max_years_vehicle_registraton_before_start_date" text,
    "elig_dealer_opt_in_renewal_2021" text,
    "elig_dealer_opt_in_os_2023_1" text,
    "elig_dealer_opt_in_os_2023_2" text,
    "elig_no_used_cars" text,
    "elig_no_commercial_cars" text,
    "elig_no_used_nor_commercial_cars" text,
    "repl_min_weighted_avg_interest_rate" text,
    "repl_max_used_car_penetration" text,
    "repl_max_commercial_car_penetration" text,
    "repl_max_commercial_used_car_penetration" text,
    "repl_max_moto_lcv_penetration" text,
    "repl_max_residual_value_penetration" text,
    "repl_max_largest_lessee" text,
    "repl_max_largest_rv_dealer" text,
    "repl_max_largest_car_brand" text,
    "elig_status_red_pool" text,
    "elig_at_least_n_instalments_red_pool" text,
    "elig_max_vehicle_weight_red_pool" text,
    "elig_max_outstanding_balance_red_pool" text,
    "elig_min_outstanding_balance_red_pool" text,
    "elig_min_interest_rate_red_pool" text,
    "elig_max_ratio_residual_value_red_pool" text,
    "elig_min_months_until_termination_red_pool" text,
    "elig_min_lease_term_red_pool" text,
    "elig_max_lease_term_red_pool" text,
    "elig_max_delinquency_bucket_red_pool" text,
    "elig_min_contract_start_date_red_pool" text,
    "elig_max_residual_value_red_pool" text,
    "elig_max_financed_amount_net_red_pool" text,
    "elig_min_days_vehicle_registration_before_start_date_red_pool" text,
    "elig_max_years_vehicle_registraton_before_start_date_red_pool" text,
    "elig_dealer_opt_in_red_pool" text,
    "elig_dealer_agb_check_red_pool" text,
    "elig_not_umschreibung" text,
    "elig_restwertverlaengerung_rv_greater_than_deposit" text,
    "modified" text,
    "modified_by_whom" text,
    "sha256" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text,
    "repl_max_delinquency" text,
    "repl_max_gross_write_off" text
);

-- Table: hist_eng_eligibility_restrictions_tc
CREATE TABLE "hist_eng_eligibility_restrictions_tc" (
    "period_" text,
    "sysperson_spv" text,
    "strategic_partner" text,
    "min_agb_version_sortable_leasing" text,
    "min_agb_version_sortable_umschreibung" text,
    "min_agb_version_sortable_rw_verl" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_id_mapping_person
CREATE TABLE "hist_eng_id_mapping_person" (
    "sysperson" text,
    "id_blurred" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_id_mapping_vt
CREATE TABLE "hist_eng_id_mapping_vt" (
    "sysvt" text,
    "vt_vertrag" text,
    "sysperson_lessee" text,
    "car_typ" text,
    "ob_typ" text,
    "vehicle_has_engine" text,
    "car_brand" text,
    "car_model" text,
    "retail_purchase_price" text,
    "residual_value_net" text,
    "residual_value_incl_vat" text,
    "lease_term" text,
    "agb_version_sortable" text,
    "product_type" text,
    "sunken_since_period" text,
    "id_blurred" text,
    "product_type_" text,
    "agb_version" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_result_replenishment_criteria_check_v
CREATE TABLE "hist_eng_result_replenishment_criteria_check_v" (
    "sysperson_spv" text,
    "period_" text,
    "status_spv" text,
    "txt" text,
    "actual_value" text,
    "config_value" text,
    "flg" text,
    "limit_type" text,
    "tag" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_servicer_report_result
CREATE TABLE "hist_eng_servicer_report_result" (
    "sysperson_spv" text,
    "dt" text,
    "period_" text,
    "tag" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_servicer_report_result_defaults
CREATE TABLE "hist_eng_servicer_report_result_defaults" (
    "producing_month" text,
    "reporting_month" text,
    "total_replenishment_amount_cumulative" text,
    "new_defaults_in_month" text,
    "cumulative_defaults" text,
    "cumulative_defaults_pct" text,
    "recoveries_in_month" text,
    "cumulative_recoveries" text,
    "recoveries_pct" text,
    "period_" text,
    "tag" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_servicer_report_result_delinquencies
CREATE TABLE "hist_eng_servicer_report_result_delinquencies" (
    "col_1" text,
    "col_2" text,
    "col_3" text,
    "period_" text,
    "tag" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_servicer_report_result_pool_information
CREATE TABLE "hist_eng_servicer_report_result_pool_information" (
    "col_1" text,
    "col_2" text,
    "period_" text,
    "tag" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_servicer_report_result_stratification
CREATE TABLE "hist_eng_servicer_report_result_stratification" (
    "table_" text,
    "level_" text,
    "text" text,
    "total_outstanding_balance_chf" text,
    "total_outstanding_balance_pct" text,
    "total_residual_value_chf" text,
    "total_residual_value_pct" text,
    "total_number_of_assets" text,
    "total_number_of_assets_pct" text,
    "sort_order" text,
    "period_" text,
    "tag" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_vt_selection_period
CREATE TABLE "hist_eng_vt_selection_period" (
    "period_" text,
    "sysvt" text,
    "status_spv" text,
    "sysperson_spv" text,
    "settlement_date" text,
    "ob_bezeichnung" text,
    "vehicle_weight" text,
    "engine" text,
    "outstanding_balance" text,
    "balance_op" text,
    "repurchase_balance" text,
    "downpayment" text,
    "downpayment_ex_vat" text,
    "flag_ppi" text,
    "nof_soll_rate_bezahlt" text,
    "vt_ende" text,
    "end_date_lease_contract" text,
    "interest_nominal" text,
    "interest_effective" text,
    "sysperson_dealer" text,
    "dealer_group_id" text,
    "dealer_group_name" text,
    "dealer_opt_in_renewal_2021" text,
    "dealer_opt_in_os_2023_1" text,
    "dealer_opt_in_os_2023_2" text,
    "dealer_is_lessee" text,
    "bn_employee" text,
    "cs_employee" text,
    "vt_restructured" text,
    "zustand_vt" text,
    "attribut_vt" text,
    "lessee_residency" text,
    "client_type" text,
    "date_vehicle_registration" text,
    "start_date_lease" text,
    "vt_ausdatum" text,
    "deposit" text,
    "financed_amount_net" text,
    "monthly_instalment" text,
    "channel_origination" text,
    "risk_class" text,
    "auslausweis" text,
    "months_on_book" text,
    "kkg_contract" text,
    "kanton" text,
    "rian_wb_delq" text,
    "write_off_amount" text,
    "cash_sweep_amount" text,
    "car_is_repossessed" text,
    "strategic_partner" text,
    "km_contract_start" text,
    "km_per_year" text,
    "sha256" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_vt_selection_period_landing
CREATE TABLE "hist_eng_vt_selection_period_landing" (
    "period_" text,
    "vt_vertrag" text,
    "sysperson_lessee" text,
    "sysvt" text,
    "car_typ" text,
    "ob_bezeichnung" text,
    "ob_typ" text,
    "vehicle_weight" text,
    "vehicle_has_engine" text,
    "engine" text,
    "outstanding_balance" text,
    "balance_op" text,
    "downpayment" text,
    "downpayment_ex_vat" text,
    "flag_ppi" text,
    "nof_soll_rate_bezahlt" text,
    "vt_ende" text,
    "end_date_lease_contract" text,
    "interest_nominal" text,
    "interest_effective" text,
    "sysperson_dealer" text,
    "dealer_group_id" text,
    "dealer_group_name" text,
    "dealer_opt_in_renewal_2021" text,
    "dealer_opt_in_os_2023_1" text,
    "dealer_opt_in_os_2023_2" text,
    "dealer_is_lessee" text,
    "bn_employee" text,
    "cs_employee" text,
    "car_brand" text,
    "car_model" text,
    "retail_purchase_price" text,
    "residual_value_net" text,
    "residual_value_incl_vat" text,
    "default_" text,
    "vt_restructured" text,
    "zustand_vt" text,
    "attribut_vt" text,
    "agb_version" text,
    "product_type_" text,
    "lessee_residency" text,
    "lease_term" text,
    "client_type" text,
    "date_vehicle_registration" text,
    "start_date_lease" text,
    "vt_ausdatum" text,
    "deposit" text,
    "financed_amount_net" text,
    "monthly_instalment" text,
    "channel_origination" text,
    "risk_class" text,
    "auslausweis" text,
    "kkg_contract" text,
    "kanton" text,
    "rian_wb_delq" text,
    "write_off_amount" text,
    "cash_sweep_amount" text,
    "car_is_repossessed" text,
    "strategic_partner" text,
    "km_contract_start" text,
    "km_per_year" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_eng_vt_selection_period_landing_sim
CREATE TABLE "hist_eng_vt_selection_period_landing_sim" (
    "period_" text,
    "vt_vertrag" text,
    "sysperson_lessee" text,
    "sysvt" text,
    "car_typ" text,
    "ob_bezeichnung" text,
    "ob_typ" text,
    "vehicle_weight" text,
    "vehicle_has_engine" text,
    "engine" text,
    "outstanding_balance" text,
    "balance_op" text,
    "downpayment" text,
    "downpayment_ex_vat" text,
    "flag_ppi" text,
    "nof_soll_rate_bezahlt" text,
    "vt_ende" text,
    "end_date_lease_contract" text,
    "interest_nominal" text,
    "interest_effective" text,
    "sysperson_dealer" text,
    "dealer_group_id" text,
    "dealer_group_name" text,
    "dealer_opt_in_renewal_2021" text,
    "dealer_opt_in_os_2023_1" text,
    "dealer_opt_in_os_2023_2" text,
    "dealer_is_lessee" text,
    "bn_employee" text,
    "cs_employee" text,
    "car_brand" text,
    "car_model" text,
    "retail_purchase_price" text,
    "residual_value_net" text,
    "residual_value_incl_vat" text,
    "default_" text,
    "last_default" text,
    "vt_restructured" text,
    "zustand_vt" text,
    "attribut_vt" text,
    "agb_version" text,
    "product_type_" text,
    "lessee_residency" text,
    "lease_term" text,
    "client_type" text,
    "date_vehicle_registration" text,
    "start_date_lease" text,
    "vt_ausdatum" text,
    "deposit" text,
    "financed_amount_net" text,
    "monthly_instalment" text,
    "channel_origination" text,
    "risk_class" text,
    "auslausweis" text,
    "kkg_contract" text,
    "kanton" text,
    "rian_wb_delq" text,
    "write_off_amount" text,
    "cash_sweep_amount" text,
    "car_is_repossessed" text,
    "strategic_partner" text,
    "km_contract_start" text,
    "km_per_year" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_call_exception
CREATE TABLE "hist_lib_call_exception" (
    "ts" text,
    "origin_unit" text,
    "origin_line" text,
    "err_msg" text,
    "err_nr" text,
    "call_stack_id" text,
    "id" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_call_exception_stack_error
CREATE TABLE "hist_lib_call_exception_stack_error" (
    "exception_id" text,
    "err_msg" text,
    "err_nr" text,
    "id" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_call_exception_stack_frame
CREATE TABLE "hist_lib_call_exception_stack_frame" (
    "exception_id" text,
    "unit" text,
    "line" text,
    "id" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_call_stack
CREATE TABLE "hist_lib_call_stack" (
    "ts" text,
    "id" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_call_stack_frame
CREATE TABLE "hist_lib_call_stack_frame" (
    "owner" text,
    "package" text,
    "subprogram" text,
    "line" text,
    "flg" text,
    "depth" text,
    "call_stack_id" text,
    "id" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_log
CREATE TABLE "hist_lib_log" (
    "tm" text,
    "msg" text,
    "call_stack" text,
    "node" text,
    "id" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_log_node
CREATE TABLE "hist_lib_log_node" (
    "tm" text,
    "txt" text,
    "call_stack" text,
    "parent_node" text,
    "id" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_log_plsql_block
CREATE TABLE "hist_lib_log_plsql_block" (
    "id" text,
    "exception_id" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_log_root
CREATE TABLE "hist_lib_log_root" (
    "node" text,
    "ses" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_lib_ses
CREATE TABLE "hist_lib_ses" (
    "sid" text,
    "serial#" text,
    "usr" text,
    "usr_proxy" text,
    "usr_os" text,
    "ts_earliest_known" text,
    "ts_latest_known" text,
    "id" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_meta_abs_daily_cash_sweep_buchungen_repurchased_trace
CREATE TABLE "hist_meta_abs_daily_cash_sweep_buchungen_repurchased_trace" (
    "date_processed" text,
    "fi_konto" text,
    "fi_sysfi" text,
    "id_sysfijour" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "tp" text,
    "unique_custom_id" text
);

-- Table: hist_meta_abs_daily_cash_sweep_buchungen_trace
CREATE TABLE "hist_meta_abs_daily_cash_sweep_buchungen_trace" (
    "fi_sysfi" text,
    "id_sysfijour" text,
    "fi_konto" text,
    "unique_custom_id" text,
    "date_processed" text,
    "tp" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_meta_abs_daily_cash_sweep_massenbeleg_trace
CREATE TABLE "hist_meta_abs_daily_cash_sweep_massenbeleg_trace" (
    "wj" text,
    "periode" text,
    "abs_id_sysperson_owner" text,
    "betrag" text,
    "belegart" text,
    "belegdatum" text,
    "valutadatum" text,
    "bruttobetrag" text,
    "soll_haben" text,
    "konto" text,
    "gegenkonto" text,
    "abs_status_spv" text,
    "status_settlement" text,
    "unique_custom_id_beleg" text,
    "date_processed" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_meta_abs_daily_transfer_spv_buchungen_repurchased_trace
CREATE TABLE "hist_meta_abs_daily_transfer_spv_buchungen_repurchased_trace" (
    "date_processed" text,
    "fi_konto" text,
    "fi_sysfi" text,
    "id_sysfijour" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "tp" text,
    "unique_custom_id" text
);

-- Table: hist_meta_abs_daily_transfer_spv_buchungen_trace
CREATE TABLE "hist_meta_abs_daily_transfer_spv_buchungen_trace" (
    "fi_sysfi" text,
    "id_sysfijour" text,
    "fi_konto" text,
    "unique_custom_id" text,
    "date_processed" text,
    "tp" text,
    "tech_load_date" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text
);

-- Table: hist_meta_abs_daily_transfer_spv_massenbeleg_trace
CREATE TABLE "hist_meta_abs_daily_transfer_spv_massenbeleg_trace" (
    "wj" text,
    "periode" text,
    "abs_id_sysperson_owner" text,
    "betrag" text,
    "belegart" text,
    "belegdatum" text,
    "valutadatum" text,
    "bruttobetrag" text,
    "soll_haben" text,
    "konto" text,
    "gegenkonto" text,
    "abs_status_spv" text,
    "status_settlement" text,
    "unique_custom_id_beleg" text,
    "date_processed" text,
    "tech_load_date" text,
    "tech_current_flag" text,
    "tech_valid_to" text,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" text,
    "tech_modification_date" text
);

-- Table: hist_mon_base_abs_el
CREATE TABLE "hist_mon_base_abs_el" (
    "abs_effective_date" text,
    "abs_end_date" text,
    "abs_id_sysperson_owner" text,
    "abs_inactive" text,
    "abs_name_spv" text,
    "abs_offer_date" text,
    "abs_settlement_date" text,
    "abs_status_spv" text,
    "abs_sysperson_dealer" text,
    "abs_sysperson_lessee" text,
    "antob_bezeichnung" text,
    "antrag_erfassung" text,
    "antrieb" text,
    "anz_payments" text,
    "auslausweis" text,
    "bestand" text,
    "bl_dealer_reason" text,
    "bl_vt_reason" text,
    "current_period" text,
    "date_today_sys" text,
    "daydiff_erstzul_vtbeginn" text,
    "delq" text,
    "effective_balance" text,
    "el_agb_erfassung" text,
    "el_agb_version" text,
    "el_antob_fzengine_kw" text,
    "el_antob_fzengine_treibstoff" text,
    "el_anz_payments" text,
    "el_blacklist_dealer" text,
    "el_blacklist_vt" text,
    "el_brand" text,
    "el_brand_desc" text,
    "el_changedvtende" text,
    "el_cond_ma_csg" text,
    "el_cond_ma_neu" text,
    "el_dealer_optin" text,
    "el_delq" text,
    "el_employee_cs_alt" text,
    "el_extratcode" text,
    "el_extratcode_desc" text,
    "el_fzgew" text,
    "el_fzleergew" text,
    "el_fztyp" text,
    "el_fztyp_desc" text,
    "el_fzzulgew" text,
    "el_kd_eq_hd" text,
    "el_kd_eq_hdvk" text,
    "el_kd_eq_hdvk_identeg" text,
    "el_kd_eq_hd_identeg" text,
    "el_maxvtnetfinamount" text,
    "el_maxvtrelrw" text,
    "el_maxvtrw" text,
    "el_max_rkl" text,
    "el_mindiffvtende" text,
    "el_minvtbeginn" text,
    "el_minvtzinseff" text,
    "el_ob_fzengine_bez" text,
    "el_ob_regdate_144months" text,
    "el_ob_regdate_45days" text,
    "el_permit" text,
    "el_pkz_employee_bn" text,
    "el_pkz_employee_cs" text,
    "el_residency_ch" text,
    "el_vart" text,
    "el_vart_desc" text,
    "el_vtglz_6" text,
    "el_vtglz_60" text,
    "el_vthistzustattr" text,
    "el_vttyp" text,
    "el_vttyp_desc" text,
    "el_vtzustattr" text,
    "el_vt_saldo_200k" text,
    "el_vt_saldo_5k" text,
    "erstzul" text,
    "extratingcode" text,
    "fztyp" text,
    "identeg_hd" text,
    "identeg_kd" text,
    "identeg_vk" text,
    "is_blacklisted" text,
    "is_deflagged" text,
    "kw" text,
    "last_existing_period" text,
    "leergew" text,
    "list_roleattrib_name" text,
    "min_relevant_period" text,
    "mitarbeiterflag" text,
    "mondiff_erstzul_vtbeginn" text,
    "mondiff_vtende" text,
    "motor" text,
    "nationalitaet_iso" text,
    "nationalitaet_name" text,
    "objektart" text,
    "ob_bezeichnung" text,
    "ob_hersteller" text,
    "person_commercialflag" text,
    "privatflag" text,
    "prodcondition_ma" text,
    "prodcondname" text,
    "rkl_max" text,
    "sysantrag" text,
    "sysbrand" text,
    "sysland" text,
    "sysprproduct" text,
    "sysvart" text,
    "sysvttyp" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "treibstoff" text,
    "vtattribut" text,
    "vtbeginn" text,
    "vtbgextern" text,
    "vtdatabschluss" text,
    "vtende" text,
    "vtglz" text,
    "vthistattribut" text,
    "vthistzustand" text,
    "vtnetfinamount" text,
    "vtobhd_syshd" text,
    "vtrelrw" text,
    "vtrw" text,
    "vtsz" text,
    "vtzinseff" text,
    "vtzustand" text,
    "vt_agb_version" text,
    "vt_agb_version_raw" text,
    "vt_sysid" text,
    "vt_syskd" text,
    "vt_sysvk" text,
    "vt_vertrag" text,
    "wohnsitzland_iso" text,
    "wohnsitzland_name" text,
    "zulgew" text,
    "deposit" text,
    "residual_value_net" text,
    "produktart" text,
    "el_vt_saldo_150k" text,
    "el_minvtzinseff_2" text,
    "el_brand_spv2" text,
    "el_agb_version_spv2" text,
    "el_agb_erfassung_spv2" text,
    "effective_interest" text,
    "reporting_include_for_rv" text
);

-- Table: hist_mon_el_calc
CREATE TABLE "hist_mon_el_calc" (
    "abs_id_sysperson_owner" text,
    "abs_inactive" text,
    "abs_name_spv" text,
    "abs_status_spv" text,
    "current_period" text,
    "el_001" text,
    "el_002" text,
    "el_003" text,
    "el_004" text,
    "el_005" text,
    "el_006_spv1" text,
    "el_006_spv2" text,
    "el_007" text,
    "el_008" text,
    "el_009" text,
    "el_010" text,
    "el_011" text,
    "el_012" text,
    "el_013" text,
    "el_014_spv1" text,
    "el_014_spv2" text,
    "el_015" text,
    "el_016" text,
    "el_017" text,
    "el_018" text,
    "el_019" text,
    "el_020" text,
    "el_021" text,
    "el_022" text,
    "el_023" text,
    "el_024_spv1" text,
    "el_024_spv2" text,
    "el_025_1_spv1" text,
    "el_025_1_spv2" text,
    "el_025_2_spv1" text,
    "el_025_2_spv2" text,
    "el_026" text,
    "el_027" text,
    "el_028" text,
    "el_029" text,
    "el_030" text,
    "el_031" text,
    "el_032" text,
    "el_033" text,
    "el_034" text,
    "el_035" text,
    "el_all_ok_spv1" text,
    "el_all_ok_spv2" text,
    "el_count_spv1" text,
    "el_count_spv2" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text,
    "vt_sysid" text,
    "vt_vertrag" text
);

-- Table: hist_mon_rp_calc
CREATE TABLE "hist_mon_rp_calc" (
    "abs_id_sysperson_owner" text,
    "abs_inactive" text,
    "abs_name_spv" text,
    "abs_status_spv" text,
    "current_period" text,
    "rp_criteria" text,
    "rp_justification" text,
    "rp_limit_utilization" text,
    "rp_name" text,
    "status_ok_nok" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text
);

-- Table: hist_placeholder
CREATE TABLE "hist_placeholder" (
    "placeholder" text,
    "tech_bk" text,
    "tech_current_flag" text,
    "tech_load_date" text,
    "tech_modification_date" text,
    "tech_pk" text,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" text
);

-- Table: meta_abs_processing_status
CREATE TABLE "meta_abs_processing_status" (
    "execution_group" text,
    "order_date" text,
    "status" text,
    "log_run_id" text,
    "message" text,
    "job_name" text,
    "meta_abs_processing_status_id" text,
    "tech_load_date" text
);

-- Table: meta_execution_groups_config
CREATE TABLE "meta_execution_groups_config" (
    "execution_group" text,
    "scheduling_type" text,
    "execution_order" text,
    "tech_load_date" text
);

