-- Table: hist_abs_daily_cash_sweep_massenbeleg_settled_out
CREATE TABLE "hist_abs_daily_cash_sweep_massenbeleg_settled_out" (
    "abs_id_sysperson_owner" integer,
    "abs_status_spv" text,
    "affiliate_gkonto" text,
    "affiliate_konto" text,
    "belegart" integer,
    "belegdatum" timestamp without time zone,
    "betrag" numeric,
    "bruttobetrag" numeric,
    "buchungsart" integer,
    "buchungsjahr" integer,
    "buchungsmonat" integer,
    "einzug" text,
    "einzug_datum" text,
    "esr" text,
    "gegenkonto" text,
    "gutschrift" text,
    "konto" text,
    "kst" text,
    "mass" text,
    "mwst_code" integer,
    "objekt" text,
    "periode" integer,
    "p_kst" text,
    "rechnungsnummer" text,
    "soll_haben" text,
    "status_settlement" text,
    "steuerbetrag" text,
    "tech_bk" text,
    "tech_current_flag" integer,
    "tech_load_date" timestamp without time zone,
    "tech_modification_date" timestamp without time zone,
    "tech_pk" integer,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" integer,
    "tech_valid_from" timestamp without time zone,
    "tech_valid_to" timestamp without time zone,
    "text" text,
    "unique_custom_id_beleg" text,
    "valutadatum" timestamp without time zone,
    "vertrag" text,
    "wj" integer,
    "zahlungsvereinbarung" text,
    "zinsrelevant" integer
);

-- Table: hist_cfg_eligibility_criticality
CREATE TABLE "hist_cfg_eligibility_criticality" (
    "binding" text,
    "criticality" text,
    "el_criteria" text,
    "el_name" text,
    "inserted" timestamp without time zone,
    "inserted_by" text,
    "tech_current_flag" integer,
    "tech_load_date" timestamp without time zone,
    "tech_modification_date" timestamp without time zone,
    "tech_pk" integer,
    "tech_record_type" text,
    "tech_runid_close" text,
    "tech_runid_create" text,
    "tech_valid_from" text,
    "tech_valid_to" timestamp without time zone
);

-- Table: hist_cfg_spv_values
CREATE TABLE "hist_cfg_spv_values" (
    "sysperson_spv" integer,
    "name_spv" text,
    "revolving_period_start" text,
    "revolving_period_end" text,
    "target_balance" numeric,
    "precut_balance_red" integer,
    "precut_balance_date" text,
    "phase" text,
    "active" text,
    "tech_load_date" timestamp without time zone,
    "tech_current_flag" integer,
    "tech_valid_to" timestamp without time zone,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" integer,
    "tech_modification_date" timestamp without time zone
);

-- Table: hist_eng_abs_period_run
CREATE TABLE "hist_eng_abs_period_run" (
    "period_" text,
    "opened_date" text,
    "closed_date" text,
    "asset_basis_run_exec_date" timestamp without time zone,
    "asset_basis_run_per_date" timestamp without time zone,
    "status_" text,
    "tech_load_date" timestamp without time zone,
    "tech_current_flag" integer,
    "tech_valid_to" timestamp without time zone,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" integer,
    "tech_modification_date" timestamp without time zone
);

-- Table: hist_eng_abs_run_per_spv_period
CREATE TABLE "hist_eng_abs_run_per_spv_period" (
    "period_" text,
    "sysperson_spv" integer,
    "run_type" text,
    "select_run_exec_date" text,
    "sell_run_exec_date" text,
    "settlement_date" text,
    "balance_target" text,
    "replenishment_target" text,
    "replenishment_actual" text,
    "elig_at_least_n_instalments" integer,
    "elig_max_vehicle_weight" integer,
    "elig_max_outstanding_balance" integer,
    "elig_min_outstanding_balance" integer,
    "elig_min_interest_rate" integer,
    "elig_max_ratio_residual_value" numeric,
    "elig_min_months_until_termination" integer,
    "elig_min_lease_term" integer,
    "elig_max_lease_term" integer,
    "elig_max_delinquency_bucket" integer,
    "elig_min_contract_start_date" timestamp without time zone,
    "elig_max_residual_value" integer,
    "elig_max_financed_amount_net" integer,
    "elig_min_days_vehicle_registration_before_start_date" integer,
    "elig_max_years_vehicle_registraton_before_start_date" integer,
    "elig_dealer_opt_in_renewal_2021" text,
    "elig_dealer_opt_in_os_2023_1" text,
    "elig_dealer_opt_in_os_2023_2" text,
    "elig_no_used_cars" text,
    "elig_no_commercial_cars" text,
    "elig_no_used_nor_commercial_cars" text,
    "repl_min_weighted_avg_interest_rate" text,
    "repl_max_used_car_penetration" text,
    "repl_max_commercial_car_penetration" text,
    "repl_max_commercial_used_car_penetration" text,
    "repl_max_moto_lcv_penetration" text,
    "repl_max_residual_value_penetration" text,
    "repl_max_largest_lessee" text,
    "repl_max_largest_rv_dealer" text,
    "repl_max_largest_car_brand" text,
    "elig_status_red_pool" text,
    "elig_at_least_n_instalments_red_pool" text,
    "elig_max_vehicle_weight_red_pool" text,
    "elig_max_outstanding_balance_red_pool" text,
    "elig_min_outstanding_balance_red_pool" text,
    "elig_min_interest_rate_red_pool" text,
    "elig_max_ratio_residual_value_red_pool" text,
    "elig_min_months_until_termination_red_pool" text,
    "elig_min_lease_term_red_pool" text,
    "elig_max_lease_term_red_pool" text,
    "elig_max_delinquency_bucket_red_pool" text,
    "elig_min_contract_start_date_red_pool" text,
    "elig_max_residual_value_red_pool" text,
    "elig_max_financed_amount_net_red_pool" text,
    "elig_min_days_vehicle_registration_before_start_date_red_pool" text,
    "elig_max_years_vehicle_registraton_before_start_date_red_pool" text,
    "elig_dealer_opt_in_red_pool" text,
    "elig_dealer_agb_check_red_pool" text,
    "elig_not_umschreibung" text,
    "elig_restwertverlaengerung_rv_greater_than_deposit" text,
    "modified" timestamp without time zone,
    "modified_by_whom" text,
    "sha256" text,
    "tech_load_date" timestamp without time zone,
    "tech_current_flag" integer,
    "tech_valid_to" timestamp without time zone,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" integer,
    "tech_modification_date" timestamp without time zone,
    "repl_max_delinquency" text,
    "repl_max_gross_write_off" text
);

-- Table: hist_lib_call_exception
CREATE TABLE "hist_lib_call_exception" (
    "ts" text,
    "origin_unit" text,
    "origin_line" integer,
    "err_msg" text,
    "err_nr" integer,
    "call_stack_id" integer,
    "id" integer,
    "tech_load_date" timestamp without time zone,
    "tech_current_flag" integer,
    "tech_valid_to" timestamp without time zone,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" integer,
    "tech_modification_date" timestamp without time zone
);

-- Table: hist_lib_call_exception_stack_error
CREATE TABLE "hist_lib_call_exception_stack_error" (
    "exception_id" integer,
    "err_msg" text,
    "err_nr" integer,
    "id" integer,
    "tech_load_date" timestamp without time zone,
    "tech_current_flag" integer,
    "tech_valid_to" timestamp without time zone,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" integer,
    "tech_modification_date" timestamp without time zone
);

-- Table: hist_lib_call_exception_stack_frame
CREATE TABLE "hist_lib_call_exception_stack_frame" (
    "exception_id" integer,
    "unit" text,
    "line" integer,
    "id" integer,
    "tech_load_date" timestamp without time zone,
    "tech_current_flag" integer,
    "tech_valid_to" timestamp without time zone,
    "tech_valid_from" text,
    "tech_runid_create" text,
    "tech_runid_close" text,
    "tech_record_type" text,
    "tech_pk" integer,
    "tech_modification_date" timestamp without time zone
);

